<template><div><h1 id="_8-监听合约事件" tabindex="-1"><a class="header-anchor" href="#_8-监听合约事件"><span>8. 监听合约事件</span></a></h1>
<h2 id="监听合约事件" tabindex="-1"><a class="header-anchor" href="#监听合约事件"><span>监听合约事件</span></a></h2>
<h3 id="contract-on" tabindex="-1"><a class="header-anchor" href="#contract-on"><span><code v-pre>contract.on</code></span></a></h3>
<p>在<code v-pre>ethersjs</code>中，合约对象有一个<code v-pre>contract.on</code>的监听方法，让我们持续监听合约的事件：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"eventName"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><code v-pre>contract.on</code>有两个参数，一个是要监听的事件名称<code v-pre>&quot;eventName&quot;</code>，需要包含在合约<code v-pre>abi</code>中；另一个是我们在事件发生时调用的函数。</p>
<h3 id="contract-once" tabindex="-1"><a class="header-anchor" href="#contract-once"><span>contract.once</span></a></h3>
<p>合约对象有一个<code v-pre>contract.once</code>的监听方法，让我们只监听一次合约释放事件，它的参数与<code v-pre>contract.on</code>一样：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span><span class="token function">once</span><span class="token punctuation">(</span><span class="token string">"eventName"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="监听usdt合约" tabindex="-1"><a class="header-anchor" href="#监听usdt合约"><span>监听<code v-pre>USDT</code>合约</span></a></h2>
<ol>
<li>声明<code v-pre>provider</code>：Alchemy是一个免费的ETH节点提供商。需要先申请一个，后续会用到。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 准备 alchemy API</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-mainnet.g.alchemy.com/v2/oKmOQKbneVkxgHZfibs-iFhIlIAl6HDN'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 连接主网 provider</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="2">
<li>声明合约变量：我们只关心<code v-pre>USDT</code>合约的<code v-pre>Transfer</code>事件，把它填入到<code v-pre>abi</code>中就可以。如果你关心其他函数和事件的话，可以在<a href="https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code" target="_blank" rel="noopener noreferrer">etherscan</a>上找到。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// USDT的合约地址</span></span>
<span class="line"><span class="token keyword">const</span> contractAddress <span class="token operator">=</span> <span class="token string">'0xdac17f958d2ee523a2206206994597c13d831ec7'</span></span>
<span class="line"><span class="token comment">// 构建USDT的Transfer的ABI</span></span>
<span class="line"><span class="token keyword">const</span> abi <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">  <span class="token string">"event Transfer(address indexed from, address indexed to, uint value)"</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 生成USDT合约对象</span></span>
<span class="line"><span class="token keyword">const</span> contractUSDT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>contractAddress<span class="token punctuation">,</span> abi<span class="token punctuation">,</span> provider<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="3">
<li>利用<code v-pre>contract.once()</code>函数，监听一次<code v-pre>Transfer</code>事件，并打印结果。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">  <span class="token comment">// 只监听一次</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 利用contract.once()，监听一次Transfer事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  contractUSDT<span class="token punctuation">.</span><span class="token function">once</span><span class="token punctuation">(</span><span class="token string">'Transfer'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">from<span class="token punctuation">,</span> to<span class="token punctuation">,</span> value</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 打印结果</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">      <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">from</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>to<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/8-1.png" alt="只监听一次"></p>
<ol start="4">
<li>利用<code v-pre>contract.on()</code>函数，持续监听<code v-pre>Transfer</code>事件，并打印结果。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">  <span class="token comment">// 持续监听USDT合约</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 利用contract.on()，持续监听Transfer事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'Transfer'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">from<span class="token punctuation">,</span> to<span class="token punctuation">,</span> value</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">     <span class="token comment">// 打印结果</span></span>
<span class="line">     <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">from</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>to<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/8-2.png" alt="持续监听"></p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 监听合约方法：</span></span>
<span class="line"><span class="token comment">// 1. 持续监听</span></span>
<span class="line"><span class="token comment">// contractUSDT.on("事件名", Listener)</span></span>
<span class="line"><span class="token comment">// 2. 只监听一次</span></span>
<span class="line"><span class="token comment">// contractUSDT.once("事件名", Listener)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 准备 alchemy API</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-mainnet.g.alchemy.com/v2/oKmOQKbneVkxgHZfibs-iFhIlIAl6HDN'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 连接主网 provider</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// USDT的合约地址</span></span>
<span class="line"><span class="token keyword">const</span> contractAddress <span class="token operator">=</span> <span class="token string">'0xdac17f958d2ee523a2206206994597c13d831ec7'</span></span>
<span class="line"><span class="token comment">// 构建USDT的Transfer的ABI</span></span>
<span class="line"><span class="token keyword">const</span> abi <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">  <span class="token string">"event Transfer(address indexed from, address indexed to, uint value)"</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 生成USDT合约对象</span></span>
<span class="line"><span class="token keyword">const</span> contractUSDT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>contractAddress<span class="token punctuation">,</span> abi<span class="token punctuation">,</span> provider<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 监听USDT合约的Transfer事件</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">try</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 只监听一次</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 利用contract.once()，监听一次Transfer事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    contractUSDT<span class="token punctuation">.</span><span class="token function">once</span><span class="token punctuation">(</span><span class="token string">'Transfer'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">from<span class="token punctuation">,</span> to<span class="token punctuation">,</span> value</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span></span>
<span class="line">      <span class="token comment">// 打印结果</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">from</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>to<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 持续监听USDT合约</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 利用contract.on()，持续监听Transfer事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'Transfer'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">from<span class="token punctuation">,</span> to<span class="token punctuation">,</span> value</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">       <span class="token comment">// 打印结果</span></span>
<span class="line">       <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">from</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>to<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">  <span class="token punctuation">}</span><span class="token keyword">catch</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


