<template><div><Layout/><h1 id="_24-识别erc20合约" tabindex="-1"><a class="header-anchor" href="#_24-识别erc20合约"><span>24. 识别ERC20合约</span></a></h1>
<p>我们介绍如何用<code v-pre>ethers.js</code>识别一个合约是否为<code v-pre>ERC20</code>标准，你会在链上分析，识别貔貅，抢开盘等场景用到它。</p>
<h2 id="erc20" tabindex="-1"><a class="header-anchor" href="#erc20"><span><code v-pre>ERC20</code></span></a></h2>
<p><code v-pre>ERC20</code> 是以太坊上最常用的代币标准，<code v-pre>ERC20</code> 标准包含以下函数和事件:</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token keyword">interface</span> <span class="token class-name">IERC20</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> value<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Approval</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> spender<span class="token punctuation">,</span> <span class="token builtin">uint256</span> value<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token builtin">address</span> account<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">transfer</span><span class="token punctuation">(</span><span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> amount<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">bool</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">allowance</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> spender<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">approve</span><span class="token punctuation">(</span><span class="token builtin">address</span> spender<span class="token punctuation">,</span> <span class="token builtin">uint256</span> amount<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">bool</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">transferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> amount<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">bool</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="识别-erc20-合约" tabindex="-1"><a class="header-anchor" href="#识别-erc20-合约"><span>识别 <code v-pre>ERC20</code> 合约</span></a></h2>
<p>在之前的<RouteLink to="/ethers/ERC721Check.html">教程</RouteLink>中，我们讲了如何基于 <code v-pre>ERC165</code> 识别 <code v-pre>ERC721</code> 合约。但是由于 <code v-pre>ERC20</code> 的发布早于 <code v-pre>ERC165</code>（20 &lt; 165），因此我们没法用相同的办法识别 <code v-pre>ERC20</code> 合约，只能另找办法。</p>
<p>区块链是公开的，我们能获取任意合约地址上的代码（bytecode）。因此，我们可以先获取合约代码，然后对比其是否包含 <code v-pre>ERC20</code> 标准中的函数就可以了。</p>
<p>首先，我们用 <code v-pre>provider</code> 的 <code v-pre>getCode()</code> 函数来取得对应地址的 <code v-pre>bytecode</code>：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">let</span> code <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getCode</span><span class="token punctuation">(</span>contractAddress<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>接下来我们要检查合约 <code v-pre>bytecode</code> 是否包含 <code v-pre>ERC20</code> 标准中的函数。合约 <code v-pre>bytecode</code> 中存储了相应的[函数选择器]：如果合约包含 <code v-pre>transfer(address, uint256)</code> 函数，那么 <code v-pre>bytecode</code> 就会包含 <code v-pre>a9059cbb</code>；如果合约包含 <code v-pre>totalSupply()</code>，那么 <code v-pre>bytecode</code> 就会包含 <code v-pre>18160ddd</code>。</p>
<p>这里，我们仅需检测  <code v-pre>transfer(address, uint256)</code> 和 <code v-pre>totalSupply()</code> 两个函数，而不用检查全部6个，这是因为：</p>
<ol>
<li><code v-pre>ERC20</code>标准中只有 <code v-pre>transfer(address, uint256)</code> 不包含在 <code v-pre>ERC721</code>标准、<code v-pre>ERC1155</code>和<code v-pre>ERC777</code>标准中。因此如果一个合约包含 <code v-pre>transfer(address, uint256)</code> 的选择器，就能确定它是 <code v-pre>ERC20</code> 代币合约，而不是其他。</li>
<li>额外检测 <code v-pre>totalSupply()</code> 是为了防止<code v-pre>选择器碰撞</code>：一串随机的字节码可能和 <code v-pre>transfer(address, uint256)</code> 的选择器（4字节）相同。</li>
</ol>
<p>代码如下</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">erc20Checker</span><span class="token punctuation">(</span><span class="token parameter">addr</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 获取合约bytecode</span></span>
<span class="line">    <span class="token keyword">let</span> code <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getCode</span><span class="token punctuation">(</span>addr<span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 非合约地址的bytecode是0x</span></span>
<span class="line">    <span class="token keyword">if</span><span class="token punctuation">(</span>code <span class="token operator">!=</span> <span class="token string">"0x"</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 检查bytecode中是否包含transfer函数和totalSupply函数的selector</span></span>
<span class="line">        <span class="token keyword">if</span><span class="token punctuation">(</span>code<span class="token punctuation">.</span><span class="token function">includes</span><span class="token punctuation">(</span><span class="token string">"a9059cbb"</span><span class="token punctuation">)</span> <span class="token operator">&amp;&amp;</span> code<span class="token punctuation">.</span><span class="token function">includes</span><span class="token punctuation">(</span><span class="token string">"18160ddd"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">            <span class="token comment">// 如果有，则是ERC20</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token boolean">true</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span></span>
<span class="line">            <span class="token comment">// 如果没有，则不是ERC20</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token boolean">false</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="测试脚本" tabindex="-1"><a class="header-anchor" href="#测试脚本"><span>测试脚本</span></a></h2>
<p>下面，我们利用 <code v-pre>DAI</code>（ERC20）和 <code v-pre>BAYC</code>（ERC721）合约来测试脚本是否能正确识别 <code v-pre>ERC20</code> 合约。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// DAI address (mainnet)</span></span>
<span class="line"><span class="token keyword">const</span> daiAddr <span class="token operator">=</span> <span class="token string">"0x6b175474e89094c44da98b954eedeac495271d0f"</span></span>
<span class="line"><span class="token comment">// BAYC address (mainnet)</span></span>
<span class="line"><span class="token keyword">const</span> baycAddr <span class="token operator">=</span> <span class="token string">"0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 检查DAI合约是否为ERC20</span></span>
<span class="line">    <span class="token keyword">let</span> isDaiERC20 <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">erc20Checker</span><span class="token punctuation">(</span>daiAddr<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">1. Is DAI a ERC20 contract: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>isDaiERC20<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 检查BAYC合约是否为ERC20</span></span>
<span class="line">    <span class="token keyword">let</span> isBaycERC20 <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">erc20Checker</span><span class="token punctuation">(</span>baycAddr<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">2. Is BAYC a ERC20 contract: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>isBaycERC20<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出如下：</p>
<p><img src="@source/ethers/img/24-1.png" alt=""></p>
<p>脚本成功检测出 <code v-pre>DAI</code> 合约是 <code v-pre>ERC20</code> 合约，而 <code v-pre>BAYC</code> 合约不是 <code v-pre>ERC20</code> 合约。</p>
<h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结"><span>总结</span></a></h2>
<p>这一讲，我们介绍了如何通过合约地址获取合约 <code v-pre>bytecode</code>，并且利用函数选择器来检测合约是否为 <code v-pre>ERC20</code> 合约。脚本能成功检测出 <code v-pre>DAI</code> 合约是 <code v-pre>ERC20</code> 合约，而 <code v-pre>BAYC</code> 合约不是 <code v-pre>ERC20</code> 合约。你会将它用在什么场景呢？</p>
</div></template>


