<template><div><Layout/><h1 id="_9-事件过滤" tabindex="-1"><a class="header-anchor" href="#_9-事件过滤"><span>9. 事件过滤</span></a></h1>
<h2 id="过滤器" tabindex="-1"><a class="header-anchor" href="#过滤器"><span>过滤器</span></a></h2>
<p>当合约创建日志（释放事件）时，它最多可以包含[4]条数据作为索引（<code v-pre>indexed</code>）。索引数据经过哈希处理并包含在<a href="https://en.wikipedia.org/wiki/Bloom_filter" target="_blank" rel="noopener noreferrer">布隆过滤器</a>中，这是一种允许有效过滤的数据结构。因此，一个事件过滤器最多包含<code v-pre>4</code>个主题集，每个主题集是个条件，用于筛选目标事件。规则：</p>
<ul>
<li>如果一个主题集为<code v-pre>null</code>，则该位置的日志主题不会被过滤，任何值都匹配。</li>
<li>如果主题集是单个值，则该位置的日志主题必须与该值匹配。</li>
<li>如果主题集是数组，则该位置的日志主题至少与数组中其中一个匹配。</li>
</ul>
<p><img src="@source/ethers/img/9-1.png" alt="过滤器规则"></p>
<h2 id="构建过滤器" tabindex="-1"><a class="header-anchor" href="#构建过滤器"><span>构建过滤器</span></a></h2>
<p><code v-pre>ethers.js</code>中的合约类提供了<code v-pre>contract.filters</code>来简化过滤器的创建：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> filter <span class="token operator">=</span> contract<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token constant">EVENT_NAME</span><span class="token punctuation">(</span> <span class="token operator">...</span>args <span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>其中<code v-pre>EVENT_NAME</code>为要过滤的事件名，<code v-pre>..args</code>为主题集/条件。前面的规则有一点抽象，下面举几个例子。</p>
<ol>
<li>过滤来自<code v-pre>myAddress</code>地址的<code v-pre>Transfer</code>事件</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span>myAddress<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><ol start="2">
<li>过滤所有发给 <code v-pre>myAddress</code>地址的<code v-pre>Transfer</code>事件</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> myAddress<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><ol start="3">
<li>过滤所有从 <code v-pre>myAddress</code>发给<code v-pre>otherAddress</code>的<code v-pre>Transfer</code>事件</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span>myAddress<span class="token punctuation">,</span> otherAddress<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><ol start="4">
<li>过滤所有发给<code v-pre>myAddress</code>或<code v-pre>otherAddress</code>的<code v-pre>Transfer</code>事件</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">contract<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token punctuation">[</span> myAddress<span class="token punctuation">,</span> otherAddress <span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="监听交易所的usdt转账" tabindex="-1"><a class="header-anchor" href="#监听交易所的usdt转账"><span>监听交易所的USDT转账</span></a></h2>
<ol>
<li>从币安交易所转出USDT的交易</li>
</ol>
<p>监听USDT合约之前，我们需要先看懂交易日志<code v-pre>Logs</code>，包括事件的<code v-pre>topics</code>和<code v-pre>data</code>。我们先找到一笔从币安交易所转出USDT的交易，然后通过hash在etherscan查它的详情：</p>
<p>交易哈希：<a href="https://etherscan.io/tx/0xab1f7b575600c4517a2e479e46e3af98a95ee84dd3f46824e02ff4618523fff5" target="_blank" rel="noopener noreferrer">0xab1f7b575600c4517a2e479e46e3af98a95ee84dd3f46824e02ff4618523fff5</a></p>
<p><img src="@source/ethers/img/9-2.png" alt="etherscan 示意图"></p>
<p>该交易做了一件事：从 <code v-pre>binance14</code> （币安热钱包）向地址<code v-pre>0x354de44bedba213d612e92d3248b899de17b0c58</code> 转账<code v-pre>2983.98</code>USDT。</p>
<p>查看该事件日志<code v-pre>Logs</code>信息：</p>
<p><img src="@source/ethers/img/9-3.png" alt="etherscan logs示意图"></p>
<ul>
<li><code v-pre>address</code>：USDT合约地址</li>
<li><code v-pre>topics[0]</code>：事件哈希，<code v-pre>keccak256(&quot;Transfer(address,address,uint256)&quot;)</code></li>
<li><code v-pre>topics[1]</code>：转出地址（币安交易所热钱包）。</li>
<li><code v-pre>topics[2]</code> 转入地址。</li>
<li><code v-pre>data</code>：转账数量。</li>
</ul>
<ol start="2">
<li>创建<code v-pre>provider</code>，<code v-pre>abi</code>，和<code v-pre>USDT</code>合约变量：</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 合约地址</span></span>
<span class="line"><span class="token keyword">const</span> addressUSDT <span class="token operator">=</span> <span class="token string">'0xdac17f958d2ee523a2206206994597c13d831ec7'</span></span>
<span class="line"><span class="token comment">// 交易所地址</span></span>
<span class="line"><span class="token keyword">const</span> accountBinance <span class="token operator">=</span> <span class="token string">'0x28C6c06298d514Db089934071355E5743bf21d60'</span></span>
<span class="line"><span class="token comment">// 构建ABI</span></span>
<span class="line"><span class="token keyword">const</span> abi <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">  <span class="token string">"event Transfer(address indexed from, address indexed to, uint value)"</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string">"function balanceOf(address) public view returns(uint)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 构建合约对象</span></span>
<span class="line"><span class="token keyword">const</span> contractUSDT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressUSDT<span class="token punctuation">,</span> abi<span class="token punctuation">,</span> provider<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol start="3">
<li>读取币安热钱包USDT余额。可以看到，当前币安热钱包有8亿多枚USDT</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> balanceUSDT <span class="token operator">=</span> <span class="token keyword">await</span> contractUSDT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>accountBinance<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">USDT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>balanceUSDT<span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/9-4.png" alt="币安热钱包USDT余额"></p>
<ol start="4">
<li>创建过滤器，监听<code v-pre>USDT</code>转入币安的事件。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 2. 创建过滤器，监听转移USDT进交易所</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 创建过滤器，监听USDT转进交易所"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">let</span> filterBinanceIn <span class="token operator">=</span> contractUSDT<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> accountBinance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"过滤器详情："</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>filterBinanceIn<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span>filterBinanceIn<span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'---------监听USDT进入交易所--------'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">    <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">  <span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/9-5.png" alt="监听转入币安的USDT交易"></p>
<ol start="4">
<li>创建过滤器，监听<code v-pre>USDT</code>转出币安的交易。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">  <span class="token comment">// 3. 创建过滤器，监听交易所转出USDT</span></span>
<span class="line">  <span class="token keyword">let</span> filterToBinanceOut <span class="token operator">=</span> contractUSDT<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span>accountBinance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 创建过滤器，监听USDT转出交易所"</span><span class="token punctuation">)</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"过滤器详情："</span><span class="token punctuation">)</span></span>
<span class="line">  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>filterToBinanceOut<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span>filterToBinanceOut<span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'---------监听USDT转出交易所--------'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">      <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/9-6.png" alt="监听转出币安的USDT交易"></p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊网络</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-mainnet.g.alchemy.com/v2/oKmOQKbneVkxgHZfibs-iFhIlIAl6HDN'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 合约地址</span></span>
<span class="line"><span class="token keyword">const</span> addressUSDT <span class="token operator">=</span> <span class="token string">'0xdac17f958d2ee523a2206206994597c13d831ec7'</span></span>
<span class="line"><span class="token comment">// 交易所地址</span></span>
<span class="line"><span class="token keyword">const</span> accountBinance <span class="token operator">=</span> <span class="token string">'0x28C6c06298d514Db089934071355E5743bf21d60'</span></span>
<span class="line"><span class="token comment">// 构建ABI</span></span>
<span class="line"><span class="token keyword">const</span> abi <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">  <span class="token string">"event Transfer(address indexed from, address indexed to, uint value)"</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string">"function balanceOf(address) public view returns(uint)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 构建合约对象</span></span>
<span class="line"><span class="token keyword">const</span> contractUSDT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressUSDT<span class="token punctuation">,</span> abi<span class="token punctuation">,</span> provider<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">(</span><span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">try</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 1. 读取币安热钱包USDT余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 读取币安热钱包USDT余额"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceUSDT <span class="token operator">=</span> <span class="token keyword">await</span> contractUSDT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>accountBinance<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">USDT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>balanceUSDT<span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 2. 创建过滤器，监听转移USDT进交易所</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 创建过滤器，监听USDT转进交易所"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">let</span> filterBinanceIn <span class="token operator">=</span> contractUSDT<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> accountBinance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"过滤器详情："</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>filterBinanceIn<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span>filterBinanceIn<span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'---------监听USDT进入交易所--------'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 3. 创建过滤器，监听交易所转出USDT</span></span>
<span class="line">    <span class="token keyword">let</span> filterToBinanceOut <span class="token operator">=</span> contractUSDT<span class="token punctuation">.</span>filters<span class="token punctuation">.</span><span class="token function">Transfer</span><span class="token punctuation">(</span>accountBinance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 创建过滤器，监听USDT转出交易所"</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"过滤器详情："</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>filterToBinanceOut<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    contractUSDT<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span>filterToBinanceOut<span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'---------监听USDT转出交易所--------'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>res<span class="token punctuation">.</span>args<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">      <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


