<template><div><h1 id="_23-抢先交易脚本" tabindex="-1"><a class="header-anchor" href="#_23-抢先交易脚本"><span>23. 抢先交易脚本</span></a></h1>
<p>这一讲，我们将介绍抢先交易（Front-running，抢跑）的脚本。</p>
<p><img src="@source/ethers/img/23-1.png" alt=""></p>
<h2 id="freemint-nft合约" tabindex="-1"><a class="header-anchor" href="#freemint-nft合约"><span>Freemint NFT合约</span></a></h2>
<p>我们要抢跑的目标合约是一个ERC721标准的NFT合约<code v-pre>Frontrun.sol</code>，它拥有一个<code v-pre>mint()</code>函数进行免费铸造。</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token comment">// SPDX-License-Identifier: MIT</span></span>
<span class="line"><span class="token comment">// By 0xAA</span></span>
<span class="line"><span class="token keyword">pragma</span> <span class="token keyword">solidity</span> <span class="token operator">^</span><span class="token version number">0.8.4</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"@openzeppelin/contracts/token/ERC721/ERC721.sol"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 我们尝试frontrun一笔Free mint交易</span></span>
<span class="line"><span class="token keyword">contract</span> <span class="token class-name">FreeMint</span> <span class="token keyword">is</span> ERC721 <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">uint256</span> <span class="token keyword">public</span> totalSupply<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 构造函数，初始化NFT合集的名称、代号</span></span>
<span class="line">    <span class="token keyword">constructor</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token function">ERC721</span><span class="token punctuation">(</span><span class="token string">"Free Mint NFT"</span><span class="token punctuation">,</span> <span class="token string">"FreeMint"</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 铸造函数</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">mint</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token punctuation">{</span></span>
<span class="line">        totalSupply<span class="token operator">++</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">_mint</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span>sender<span class="token punctuation">,</span> totalSupply<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// mint</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为了简化测试环境，我们将上述合约部署在foundry本地测试网，然后监听在<code v-pre>mempool</code>中的未决交易，筛选出符合标准的交易进行抢跑。</p>
<p>安装好 foundry 后，在命令行输入以下命令就可以启动本地测试网:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line">anvil</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="抢跑脚本" tabindex="-1"><a class="header-anchor" href="#抢跑脚本"><span>抢跑脚本</span></a></h2>
<p>下面，我们详解一下抢跑脚本<code v-pre>frontrun.js</code>，这个脚本会监听链上的<code v-pre>mint()</code>交易，并发送一个gas更高的相同交易，进行抢跑。</p>
<ol>
<li>
<p>创建连接到foundry本地测试网的<code v-pre>provider</code>对象，用于监听和发送交易。foundry本地测试网默认url：<code v-pre>&quot;http://127.0.0.1:8545&quot;</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//1.连接到foundry本地网络</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>providers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token string">'&lt;http://127.0.0.1:8545>'</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">let</span> network <span class="token operator">=</span> provider<span class="token punctuation">.</span><span class="token function">getNetwork</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">network<span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">res</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]链接到网络</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>chainId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>创建合约实例，用于查看mint结果，确认是否抢跑成功。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//2.构建contract实例</span></span>
<span class="line"><span class="token keyword">const</span> contractABI <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function mint() public"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function ownerOf(uint256) public view returns (address) "</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function totalSupply() view returns (uint256)"</span></span>
<span class="line"><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> contractAddress <span class="token operator">=</span> <span class="token string">'0xC76A71C4492c11bbaDC841342C4Cb470b5d12193'</span><span class="token comment">//合约地址</span></span>
<span class="line"><span class="token keyword">const</span> contractFM <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>contractAddress<span class="token punctuation">,</span> contractABI<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>创建一个包含我们感兴趣的<code v-pre>mint()</code>函数的<code v-pre>interface</code>对象，用于在监听过程中使用。如果你不了解它，可以阅读<RouteLink to="/ethers/DecodeTx.html">WTF Ethers极简教程第20讲：解码交易</RouteLink>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//3.创建Interface对象，用于检索mint函数。</span></span>
<span class="line"><span class="token comment">//V6版本 const iface = new ethers.Interface(contractABI)</span></span>
<span class="line"><span class="token keyword">const</span> iface <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>utils<span class="token punctuation">.</span>Interface</span><span class="token punctuation">(</span>contractABI<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token parameter">fn</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line"><span class="token comment">// V6版本 return iface.getFunction("mint").selector</span></span>
<span class="line">    <span class="token keyword">return</span> iface<span class="token punctuation">.</span><span class="token function">getSighash</span><span class="token punctuation">(</span>fn<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>创建测试钱包，用于发送抢跑交易，私钥是foundry测试网提供的，里面有10000 ETH测试币。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//4. 创建测试钱包，用于发送抢跑交易，私钥是foundry测试网提供</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>我们先看一下正常的mint结果是怎样的。我们利用<code v-pre>provider.on</code>方法监听mempool中的未决交易，当交易出现时，我们会利用交易哈希<code v-pre>txHash</code>来读取交易详情<code v-pre>tx</code>，并筛选出调用了<code v-pre>mint()</code>函数的交易，查看交易结果，获取mint的nft编码及对应的owner，比对交易发起地址与owner是否一致。确认，mint按预期执行。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//5. 构建正常mint函数，检验mint结果，显示正常。</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">normaltx</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">provider<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'pending'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">txHash</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    provider<span class="token punctuation">.</span><span class="token function">getTransaction</span><span class="token punctuation">(</span>txHash<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">tx</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span>tx<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token string">"mint"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]监听到交易:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//打印交易发起地址</span></span>
<span class="line">                <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">                <span class="token keyword">const</span> tokenId <span class="token operator">=</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">                console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint的NFT编号:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">NFT的持有者是</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>tokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//打印nft持有者地址</span></span>
<span class="line">                console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是不是对应NFT的持有者:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from <span class="token operator">===</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>tokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//比较二者是否一致</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/23-2.png" alt=""></p>
</li>
<li>
<p>进行抢跑mint。我们依旧利用<code v-pre>provider.on</code>方法监听mempool中的未决交易，当有调用了mint()函数的交易出现且发送方不是自己钱包地址的交易（如果不筛选，会自己抢跑自己的交易，陷入死循环）时，构建抢跑交易，发送交易进行抢跑。等待交易结束后，查看抢跑结果。预期将要被mint的nft并未被原交易发起地址mint，而是由抢跑地址mint。同时查看区块内数据，抢跑交易在原始交易前被打包进区块，抢跑成功！</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> <span class="token function-variable function">frontRun</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">provider<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'pending'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">txHash</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransaction</span><span class="token punctuation">(</span>txHash<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>tx<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token string">"mint"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span> <span class="token operator">&amp;&amp;</span> tx<span class="token punctuation">.</span>from <span class="token operator">!==</span> wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]监听到交易:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n准备抢先交易</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">const</span> frontRunTx <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">to</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>to<span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">value</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>value<span class="token punctuation">,</span></span>
<span class="line"><span class="token comment">// V6版本 maxPriorityFeePerGas: tx.maxPriorityFeePerGas * 2n， 其他运算同理。参考https://docs.ethers.org/v6/migrating/#migrate-bigint</span></span>
<span class="line">            <span class="token literal-property property">maxPriorityFeePerGas</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>maxPriorityFeePerGas<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">maxFeePerGas</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>maxFeePerGas<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">gasLimit</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>gasLimit<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token literal-property property">data</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>data</span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">const</span> aimTokenId <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">即将被mint的NFT编号是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//打印应该被mint的nft编号</span></span>
<span class="line">        <span class="token keyword">const</span> sentFR <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">sendTransaction</span><span class="token punctuation">(</span>frontRunTx<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">正在frontrun交易</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">const</span> receipt <span class="token operator">=</span> <span class="token keyword">await</span> sentFR<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">frontrun 交易成功,交易hash是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>receipt<span class="token punctuation">.</span>transactionHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">NFT的持有者是</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//刚刚mint的nft持有者并不是tx.from</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">的NFT的持有者是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//tx.from被wallet.address抢跑，mint了下一个nft</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是不是对应NFT的持有者:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from <span class="token operator">===</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//比对地址，tx.from被抢跑</span></span>
<span class="line">        <span class="token comment">//检验区块内数据结果</span></span>
<span class="line">        <span class="token keyword">const</span> block <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBlock</span><span class="token punctuation">(</span>tx<span class="token punctuation">.</span>blockNumber<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">区块内交易数据明细:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>block<span class="token punctuation">.</span>transactions<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//在区块内，后发交易排在先发交易前，抢跑成功。</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/23-3.png" alt=""></p>
</li>
</ol>
<h2 id="合约代码" tabindex="-1"><a class="header-anchor" href="#合约代码"><span>合约代码</span></a></h2>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token comment">// SPDX-License-Identifier: MIT</span></span>
<span class="line"><span class="token keyword">pragma</span> <span class="token keyword">solidity</span> <span class="token operator">^</span><span class="token version number">0.8.4</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"@openzeppelin/contracts/token/ERC721/ERC721.sol"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 我们尝试frontrun一笔Free mint交易</span></span>
<span class="line"><span class="token keyword">contract</span> <span class="token class-name">FreeMint</span> <span class="token keyword">is</span> ERC721 <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">uint256</span> <span class="token keyword">public</span> totalSupply<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 构造函数，初始化NFT合集的名称、代号</span></span>
<span class="line">    <span class="token keyword">constructor</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token function">ERC721</span><span class="token punctuation">(</span><span class="token string">"Free Mint NFT"</span><span class="token punctuation">,</span> <span class="token string">"FreeMint"</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 铸造函数</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">mint</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token punctuation">{</span></span>
<span class="line">        totalSupply<span class="token operator">++</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">_mint</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span>sender<span class="token punctuation">,</span> totalSupply<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// mint</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="脚本代码" tabindex="-1"><a class="header-anchor" href="#脚本代码"><span>脚本代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//1.连接到foundry本地网络</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// V6 版本 const provider = new ethers.JsonRpcProvider('http://127.0.0.1:8545')</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>providers<span class="token punctuation">.</span>WebSocketProvider</span><span class="token punctuation">(</span><span class="token string">'http://127.0.0.1:8545'</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">let</span> network <span class="token operator">=</span> provider<span class="token punctuation">.</span><span class="token function">getNetwork</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">network<span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">res</span> <span class="token operator">=></span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]链接到网络</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>res<span class="token punctuation">.</span>chainId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//2.构建contract实例</span></span>
<span class="line"><span class="token keyword">const</span> contractABI <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function mint() public"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function ownerOf(uint256) public view returns (address) "</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function totalSupply() view returns (uint256)"</span></span>
<span class="line"><span class="token punctuation">]</span></span>
<span class="line"><span class="token keyword">const</span> contractAddress <span class="token operator">=</span> <span class="token string">'0xC76A71C4492c11bbaDC841342C4Cb470b5d12193'</span></span>
<span class="line"><span class="token keyword">const</span> contractFM <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>contractAddress<span class="token punctuation">,</span> contractABI<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//3.创建Interface对象，用于检索mint函数。</span></span>
<span class="line"><span class="token keyword">const</span> iface <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>utils<span class="token punctuation">.</span>Interface</span><span class="token punctuation">(</span>contractABI<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token parameter">fn</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// V6 版本 return iface.getFunction("mint").selector</span></span>
<span class="line">    <span class="token keyword">return</span> iface<span class="token punctuation">.</span><span class="token function">getSighash</span><span class="token punctuation">(</span>fn<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//4. 创建测试钱包，用于发送抢跑交易，私钥是foundry测试网提供</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//5. 构建正常mint函数，检验mint结果，显示正常。</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">normaltx</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    provider<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'pending'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">txHash</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        provider<span class="token punctuation">.</span><span class="token function">getTransaction</span><span class="token punctuation">(</span>txHash<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span></span>
<span class="line">            <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">tx</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span>tx<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token string">"mint"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]监听到交易:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                    <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">                    <span class="token keyword">const</span> tokenId <span class="token operator">=</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">                    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint的NFT编号:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">NFT的持有者是</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>tokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是不是对应NFT的持有者:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from <span class="token operator">===</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>tokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">//6.构建抢跑交易，检验mint结果，抢跑成功！</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">frontRun</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    provider<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'pending'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token parameter">txHash</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransaction</span><span class="token punctuation">(</span>txHash<span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>tx<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token function">getSignature</span><span class="token punctuation">(</span><span class="token string">"mint"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span> <span class="token operator">&amp;&amp;</span> tx<span class="token punctuation">.</span>from <span class="token operator">!==</span> wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleTimeString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]监听到交易:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n准备抢先交易</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">            <span class="token keyword">const</span> frontRunTx <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token literal-property property">to</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>to<span class="token punctuation">,</span></span>
<span class="line">                <span class="token literal-property property">value</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>value<span class="token punctuation">,</span></span>
<span class="line">                <span class="token comment">// V6版本 maxPriorityFeePerGas: tx.maxPriorityFeePerGas * 2n， 其他运算同理。参考https://docs.ethers.org/v6/migrating/#migrate-bigint</span></span>
<span class="line">                <span class="token literal-property property">maxPriorityFeePerGas</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>maxPriorityFeePerGas<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">                <span class="token literal-property property">maxFeePerGas</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>maxFeePerGas<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">                <span class="token literal-property property">gasLimit</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>gasLimit<span class="token punctuation">.</span><span class="token function">mul</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">                <span class="token literal-property property">data</span><span class="token operator">:</span> tx<span class="token punctuation">.</span>data</span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">            <span class="token keyword">const</span> aimTokenId <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">即将被mint的NFT编号是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//打印应该被mint的nft编号</span></span>
<span class="line">            <span class="token keyword">const</span> sentFR <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">sendTransaction</span><span class="token punctuation">(</span>frontRunTx<span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">正在frontrun交易</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">            <span class="token keyword">const</span> receipt <span class="token operator">=</span> <span class="token keyword">await</span> sentFR<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">frontrun 交易成功,交易hash是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>receipt<span class="token punctuation">.</span>transactionHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">NFT的持有者是</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//刚刚mint的nft持有者并不是tx.from</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">编号</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>aimTokenId<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">的NFT的持有者是:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//tx.from被wallet.address抢跑，mint了下一个nft</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">铸造发起的地址是不是对应NFT的持有者:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tx<span class="token punctuation">.</span>from <span class="token operator">===</span> <span class="token keyword">await</span> contractFM<span class="token punctuation">.</span><span class="token function">ownerOf</span><span class="token punctuation">(</span>aimTokenId<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//比对地址，tx.from被抢跑</span></span>
<span class="line">            <span class="token comment">//检验区块内数据结果</span></span>
<span class="line">            <span class="token keyword">const</span> block <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBlock</span><span class="token punctuation">(</span>tx<span class="token punctuation">.</span>blockNumber<span class="token punctuation">)</span></span>
<span class="line">            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">区块内交易数据明细:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>block<span class="token punctuation">.</span>transactions<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token comment">//在区块内，后发交易排在先发交易前，抢跑成功。</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token function">frontRun</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


