<template><div><Layout/><h1 id="_17-merkletree脚本" tabindex="-1"><a class="header-anchor" href="#_17-merkletree脚本"><span>17. MerkleTree脚本</span></a></h1>
<p>这一讲我们写一个利用<code v-pre>Merkle Tree</code>白名单铸造<code v-pre>NFT</code>的脚本，如果你对<code v-pre>Merkle Tree</code>合约不熟悉.</p>
<h2 id="merkle-tree" tabindex="-1"><a class="header-anchor" href="#merkle-tree"><span>Merkle Tree</span></a></h2>
<p><code v-pre>Merkle Tree</code>，也叫默克尔树或哈希树，是区块链的底层加密技术，被比特币和以太坊区块链广泛采用。<code v-pre>Merkle Tree</code>是一种自下而上构建的加密树，每个叶子是对应数据的哈希，而每个非叶子为它的<code v-pre>2</code>个子节点的哈希。</p>
<p><img src="@source/ethers/img/17-1.png" alt="Merkle Tree"></p>
<p><code v-pre>Merkle Tree</code>允许对大型数据结构的内容进行有效和安全的验证（<code v-pre>Merkle Proof</code>）。对于有<code v-pre>N</code>个叶子结点的<code v-pre>Merkle Tree</code>，在已知<code v-pre>root</code>根值的情况下，验证某个数据是否有效（属于<code v-pre>Merkle Tree</code>叶子结点）只需要<code v-pre>log(N)</code>个数据（也叫<code v-pre>proof</code>），非常高效。如果数据有误，或者给的<code v-pre>proof</code>错误，则无法还原出<code v-pre>root</code>根植。下面的例子中，叶子<code v-pre>L1</code>的<code v-pre>Merkle proof</code>为<code v-pre>Hash 0-1</code>和<code v-pre>Hash 1</code>：知道这两个值，就能验证<code v-pre>L1</code>的值是不是在<code v-pre>Merkle Tree</code>的叶子中。</p>
<p><img src="@source/ethers/img/17-2.png" alt="Merkle Proof"></p>
<h2 id="merkle-tree合约简述" tabindex="-1"><a class="header-anchor" href="#merkle-tree合约简述"><span><code v-pre>Merkle Tree</code>合约简述</span></a></h2>
<p><code v-pre>MerkleTree</code>合约利用<code v-pre>Merkle Tree</code>验证白名单铸造<code v-pre>NFT</code>。我们简单讲下这里用到的两个函数：</p>
<ol>
<li>
<p>构造函数：初始化NFT的名称，代号，和<code v-pre>Merkle Tree</code>的<code v-pre>root</code>。</p>
</li>
<li>
<p><code v-pre>mint()</code>：利用<code v-pre>Merkle Proof</code>验证白名单地址并铸造。参数为白名单地址<code v-pre>account</code>，铸造的<code v-pre>tokenId</code>，和<code v-pre>proof</code>。</p>
</li>
</ol>
<h2 id="merkletree-js" tabindex="-1"><a class="header-anchor" href="#merkletree-js"><span><code v-pre>MerkleTree.js</code></span></a></h2>
<p><code v-pre>MerkleTree.js</code>是构建<code v-pre>Merkle Tree</code>和<code v-pre>Merkle Proof</code>的Javascript包（<a href="https://github.com/miguelmota/merkletreejs" target="_blank" rel="noopener noreferrer">Github连接</a>）。你可以用<code v-pre>npm</code>安装他：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> <span class="token function">install</span> merkletreejs</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这里，我们演示如何生成叶子数据包含<code v-pre>4</code>个白名单地址的<code v-pre>Merkle Tree</code>。</p>
<ol>
<li>
<p>创建白名单地址数组。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MerkleTree <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"merkletreejs"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 白名单地址</span></span>
<span class="line"><span class="token keyword">const</span> tokens <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x4B20993Bc481177ec7E8f571ceCaE8A9e22C02db"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x78731D3Ca6b7E34aC0F824c42a7cC18A495cabaB"</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>将数据进行<code v-pre>keccak256</code>哈希（与solidity使用的哈希函数匹配），创建叶子结点。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> leaf <span class="token operator">=</span> tokens<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token parameter">x</span> <span class="token operator">=></span> ethers<span class="token punctuation">.</span><span class="token function">keccak256</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>创建<code v-pre>Merkle Tree</code>，哈希函数仍然选择<code v-pre>keccak256</code>，可选参数<code v-pre>sortPairs: true</code>（<a href="https://github.com/miguelmota/merkletreejs/blob/master/docs/classes/_src_merkletree_.merkletree.md#constructor" target="_blank" rel="noopener noreferrer">constructor函数文档</a>），与<code v-pre>Merkle Tree</code>合约处理方式保持一致。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> merkletree <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">MerkleTree</span><span class="token punctuation">(</span>leaf<span class="token punctuation">,</span> ethers<span class="token punctuation">.</span>keccak256<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sortPairs</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>获得<code v-pre>Merkle Tree</code>的<code v-pre>root</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> root <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexRoot</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
<li>
<p>获得第<code v-pre>0</code>个叶子节点的<code v-pre>proof</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> proof <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexProof</span><span class="token punctuation">(</span>leaf<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></li>
</ol>
<h2 id="merkle-tree白名单铸造nft" tabindex="-1"><a class="header-anchor" href="#merkle-tree白名单铸造nft"><span><code v-pre>Merkle Tree</code>白名单铸造<code v-pre>NFT</code></span></a></h2>
<p>这里，我们举个例子，利用<code v-pre>MerkleTree.js</code>和<code v-pre>ethers.js</code>验证白名单并铸造<code v-pre>NFT</code>。</p>
<ol>
<li>
<p>生成<code v-pre>Merkle Tree</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 1. 生成merkle tree</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 生成merkle tree"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 白名单地址</span></span>
<span class="line"><span class="token keyword">const</span> tokens <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x4B20993Bc481177ec7E8f571ceCaE8A9e22C02db"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x78731D3Ca6b7E34aC0F824c42a7cC18A495cabaB"</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// leaf, merkletree, proof</span></span>
<span class="line"><span class="token keyword">const</span> leaf       <span class="token operator">=</span> tokens<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token parameter">x</span> <span class="token operator">=></span> ethers<span class="token punctuation">.</span><span class="token function">keccak256</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> merkletree <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">MerkleTree</span><span class="token punctuation">(</span>leaf<span class="token punctuation">,</span> ethers<span class="token punctuation">.</span>keccak256<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sortPairs</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> proof      <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexProof</span><span class="token punctuation">(</span>leaf<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> root <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexRoot</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Leaf:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>leaf<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nMerkleTree:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>merkletree<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nProof:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>proof<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nRoot:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>root<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/17-3.png" alt="生成Merkle Tree"></p>
</li>
<li>
<p>创建provider和wallet</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>创建合约工厂，为部署合约做准备。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 3. 创建合约工厂</span></span>
<span class="line"><span class="token comment">// NFT的abi</span></span>
<span class="line"><span class="token keyword">const</span> abiNFT <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"constructor(string memory name, string memory symbol, bytes32 merkleroot)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function mint(address account, uint256 tokenId, bytes32[] calldata proof) external"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function ownerOf(uint256) view returns (address)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 合约字节码，在remix中，你可以在两个地方找到Bytecode</span></span>
<span class="line"><span class="token comment">// i. 部署面板的Bytecode按钮</span></span>
<span class="line"><span class="token comment">// ii. 文件面板artifact文件夹下与合约同名的json文件中</span></span>
<span class="line"><span class="token comment">// 里面"object"字段对应的数据就是Bytecode，挺长的，608060起始</span></span>
<span class="line"><span class="token comment">// "object": "608060405260646000553480156100...</span></span>
<span class="line"><span class="token keyword">const</span> bytecodeNFT <span class="token operator">=</span> contractJson<span class="token punctuation">.</span>default<span class="token punctuation">.</span>object<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> factoryNFT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>ContractFactory</span><span class="token punctuation">(</span>abiNFT<span class="token punctuation">,</span> bytecodeNFT<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>利用contractFactory部署NFT合约</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 利用contractFactory部署NFT合约"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 部署合约，填入constructor的参数</span></span>
<span class="line"><span class="token keyword">const</span> contractNFT <span class="token operator">=</span> <span class="token keyword">await</span> factoryNFT<span class="token punctuation">.</span><span class="token function">deploy</span><span class="token punctuation">(</span><span class="token string">"WTF Merkle Tree"</span><span class="token punctuation">,</span> <span class="token string">"WTF"</span><span class="token punctuation">,</span> root<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>contractNFT<span class="token punctuation">.</span>target<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"等待合约部署上链"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">waitForDeployment</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"合约已上链"</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/17-4.png" alt="部署Merkle Tree合约"></p>
</li>
<li>
<p>调用<code v-pre>mint()</code>函数，利用<code v-pre>merkle tree</code>验证白名单，并给第<code v-pre>0</code>个地址铸造<code v-pre>NFT</code>。在<code v-pre>mint</code>成功后可以看到<code v-pre>NFT</code>余额变为<code v-pre>1</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 调用mint()函数，利用merkle tree验证白名单，给第一个地址铸造NFT"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">mint</span><span class="token punctuation">(</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">,</span> proof<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"铸造中，等待交易上链"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint成功，地址</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> 的NFT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/17-5.png" alt="白名单铸造"></p>
</li>
</ol>
<h2 id="用于生产环境" tabindex="-1"><a class="header-anchor" href="#用于生产环境"><span>用于生产环境</span></a></h2>
<p>在生产环境使用<code v-pre>Merkle Tree</code>验证白名单发行<code v-pre>NFT</code>主要有以下步骤：</p>
<ol>
<li>确定白名单列表。</li>
<li>在后端生成白名单列表的<code v-pre>Merkle Tree</code>。</li>
<li>部署<code v-pre>NFT</code>合约，并将<code v-pre>Merkle Tree</code>的<code v-pre>root</code>保存在合约中。</li>
<li>用户铸造时，向后端请求地址对应的<code v-pre>proof</code>。</li>
<li>用户调用<code v-pre>mint()</code>函数进行铸造<code v-pre>NFT</code>。</li>
</ol>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MerkleTree <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"merkletreejs"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token operator">*</span> <span class="token keyword">as</span> contractJson <span class="token keyword">from</span> <span class="token string">"./contract.json"</span> <span class="token keyword">assert</span> <span class="token punctuation">{</span><span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"json"</span><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 1. 生成merkle tree</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 生成merkle tree"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 白名单地址</span></span>
<span class="line"><span class="token keyword">const</span> tokens <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x4B20993Bc481177ec7E8f571ceCaE8A9e22C02db"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"0x78731D3Ca6b7E34aC0F824c42a7cC18A495cabaB"</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// leaf, merkletree, proof</span></span>
<span class="line"><span class="token keyword">const</span> leaf       <span class="token operator">=</span> tokens<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token parameter">x</span> <span class="token operator">=></span> ethers<span class="token punctuation">.</span><span class="token function">keccak256</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> merkletree <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">MerkleTree</span><span class="token punctuation">(</span>leaf<span class="token punctuation">,</span> ethers<span class="token punctuation">.</span>keccak256<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">sortPairs</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> proof      <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexProof</span><span class="token punctuation">(</span>leaf<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> root <span class="token operator">=</span> merkletree<span class="token punctuation">.</span><span class="token function">getHexRoot</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Leaf:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>leaf<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nMerkleTree:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>merkletree<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nProof:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>proof<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nRoot:"</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>root<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 2. 创建provider和wallet</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 3. 创建合约工厂</span></span>
<span class="line"><span class="token comment">// NFT的人类可读abi</span></span>
<span class="line"><span class="token keyword">const</span> abiNFT <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"constructor(string memory name, string memory symbol, bytes32 merkleroot)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function mint(address account, uint256 tokenId, bytes32[] calldata proof) external"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function ownerOf(uint256) view returns (address)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 合约字节码，在remix中，你可以在两个地方找到Bytecode</span></span>
<span class="line"><span class="token comment">// i. 部署面板的Bytecode按钮</span></span>
<span class="line"><span class="token comment">// ii. 文件面板artifact文件夹下与合约同名的json文件中</span></span>
<span class="line"><span class="token comment">// 里面"object"字段对应的数据就是Bytecode，挺长的，608060起始</span></span>
<span class="line"><span class="token comment">// "object": "608060405260646000553480156100...</span></span>
<span class="line"><span class="token keyword">const</span> bytecodeNFT <span class="token operator">=</span> contractJson<span class="token punctuation">.</span>default<span class="token punctuation">.</span>object<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> factoryNFT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>ContractFactory</span><span class="token punctuation">(</span>abiNFT<span class="token punctuation">,</span> bytecodeNFT<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 读取钱包内ETH余额</span></span>
<span class="line">    <span class="token keyword">const</span> balanceETH <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 如果钱包ETH足够</span></span>
<span class="line">    <span class="token keyword">if</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceETH<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">0.002</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 4. 利用contractFactory部署NFT合约</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 利用contractFactory部署NFT合约"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 部署合约，填入constructor的参数</span></span>
<span class="line">        <span class="token keyword">const</span> contractNFT <span class="token operator">=</span> <span class="token keyword">await</span> factoryNFT<span class="token punctuation">.</span><span class="token function">deploy</span><span class="token punctuation">(</span><span class="token string">"WTF Merkle Tree"</span><span class="token punctuation">,</span> <span class="token string">"WTF"</span><span class="token punctuation">,</span> root<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>contractNFT<span class="token punctuation">.</span>target<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"等待合约部署上链"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">waitForDeployment</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 也可以用 contractNFT.deployTransaction.wait()</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"合约已上链"</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// 5. 调用mint()函数，利用merkle tree验证白名单，给第0个地址铸造NFT</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 调用mint()函数，利用merkle tree验证白名单，给第一个地址铸造NFT"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">mint</span><span class="token punctuation">(</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">,</span> proof<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"铸造中，等待交易上链"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint成功，地址</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> 的NFT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>tokens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 如果ETH不足</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"ETH不足，去水龙头领一些Goerli ETH"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"1. alchemy水龙头: https://goerlifaucet.com/"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"2. paradigm水龙头: https://faucet.paradigm.xyz/"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


