<template><div><h1 id="provider-提供器" tabindex="-1"><a class="header-anchor" href="#provider-提供器"><span>Provider 提供器</span></a></h1>
<h2 id="provider类" tabindex="-1"><a class="header-anchor" href="#provider类"><span><code v-pre>Provider</code>类</span></a></h2>
<p><code v-pre>Provider</code>类是对以太坊网络连接的抽象，为标准以太坊节点功能提供简洁、一致的接口。在<code v-pre>ethers</code>中，<code v-pre>Provider</code>不接触用户私钥，只能读取链上信息，不能写入，这一点比<code v-pre>web3.js</code>要安全。</p>
<p>除了<a href="https://github.com/WTFAcademy/WTF-Ethers" target="_blank" rel="noopener noreferrer">之前</a>介绍的默认提供者<code v-pre>defaultProvider</code>以外，<code v-pre>ethers</code>中最常用的是<code v-pre>jsonRpcProvider</code>，可以让用户连接到特定节点服务商的节点。</p>
<h2 id="jsonrpcprovider" tabindex="-1"><a class="header-anchor" href="#jsonrpcprovider"><span><code v-pre>jsonRpcProvider</code></span></a></h2>
<h3 id="创建节点服务商的api-key" tabindex="-1"><a class="header-anchor" href="#创建节点服务商的api-key"><span>创建节点服务商的API Key</span></a></h3>
<p>首先，你需要去节点服务商的网站注册并创建<code v-pre>API Key</code>。在<code v-pre>WTF Solidity极简教程</code>的工具篇，我们介绍了<a href="https://github.com/AmazingAng/WTFSolidity/blob/main/Topics/Tools/TOOL02_Infura/readme.md" target="_blank" rel="noopener noreferrer">Infura</a>和<a href="https://github.com/AmazingAng/WTFSolidity/blob/main/Topics/Tools/TOOL04_Alchemy/readme.md" target="_blank" rel="noopener noreferrer">Alchemy</a>两家公司<code v-pre>API Key</code>的创建方法，大家可以参考。</p>
<p><img src="@source/ethers/img/2-1.png" alt="Infura API Key"></p>
<p>你还可以在 <a href="https://chainlist.org/" target="_blank" rel="noopener noreferrer">Chainlist</a> 网站找到各个链的公开节点。</p>
<h3 id="连接公开节点" tabindex="-1"><a class="header-anchor" href="#连接公开节点"><span>连接公开节点</span></a></h3>
<p>这里，我们用<a href="https://chainlist.org/" target="_blank" rel="noopener noreferrer">Chainlist</a>上的公开节点作为例子。在找到合适的rpc之后，可以利用<code v-pre>ethers.JsonRpcProvider()</code>方法来创建<code v-pre>Provider</code>变量，该方法以节点服务的<code v-pre>url</code>链接作为参数。</p>
<p>在下面这个例子中，我们分别创建连接到<code v-pre>ETH</code>主网和<code v-pre>Sepolia</code>测试网的<code v-pre>provider</code>：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 利用公共rpc节点连接以太坊网络</span></span>
<span class="line"><span class="token comment">// 可以在 https://chainlist.org 上找到</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://rpc.ankr.com/eth'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_SEPOLIA_URL</span> <span class="token operator">=</span> <span class="token string">'https://rpc.sepolia.org'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 连接以太坊主网</span></span>
<span class="line"><span class="token keyword">const</span> providerETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 连接Sepolia测试网</span></span>
<span class="line"><span class="token keyword">const</span> providerSepolia <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_SEPOLIA_URL</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="利用provider读取链上数据" tabindex="-1"><a class="header-anchor" href="#利用provider读取链上数据"><span>利用<code v-pre>Provider</code>读取链上数据</span></a></h3>
<p><code v-pre>Provider</code>类封装了一些方法，可以便捷的读取链上数据：</p>
<p><strong>1.</strong> 利用<code v-pre>getBalance()</code>函数读取主网和测试网Vitalik的<code v-pre>ETH</code>余额（测试网目前不支持<code v-pre>ENS</code>域名，只能用钱包地址查询）：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 1. 查询vitalik在主网和Sepolia测试网的ETH余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"1. 查询vitalik在主网和Sepolia测试网的ETH余额"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> balance <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">vitalik.eth</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> balanceSepolia <span class="token operator">=</span> <span class="token keyword">await</span> providerSepolia<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// 将余额输出在console（主网）</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">ETH Balance of vitalik: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balance<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// 输出Sepolia测试网ETH余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Sepolia ETH Balance of vitalik: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceSepolia<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-2.png" alt="Vitalik余额"></p>
<p><strong>2.</strong> 利用<code v-pre>getNetwork()</code>查询<code v-pre>provider</code>连接到了哪条链，<code v-pre>homestead</code>代表<code v-pre>ETH</code>主网：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 2. 查询provider连接到了哪条链</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 查询provider连接到了哪条链"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> network <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getNetwork</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>network<span class="token punctuation">.</span><span class="token function">toJSON</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>ethers v6版本, 以上代码中<code v-pre>network</code>不能直接<code v-pre>console.log()</code>, 具体原因参考: <a href="https://github.com/ethers-io/ethers.js/discussions/3977" target="_blank" rel="noopener noreferrer">discussion-3977</a></p>
</blockquote>
<p><img src="@source/ethers/img/2-3.png" alt="getNetwork"></p>
<p><strong>3.</strong> 利用<code v-pre>getBlockNumber()</code>查询当前区块高度：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 3. 查询区块高度</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 查询区块高度"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> blockNumber <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBlockNumber</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>blockNumber<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-4.png" alt="getBlockNumber"></p>
<p><strong>4.</strong> 利用<code v-pre>getTransactionCount()</code>查询某个钱包的历史交易次数。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 4. 查询 vitalik 钱包历史交易次数</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n4. 查询 vitalik 钱包历史交易次数"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> txCount <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span><span class="token string">"vitalik.eth"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>txCount<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-5.png" alt="getGasPrice"></p>
<p><strong>5.</strong> 利用<code v-pre>getFeeData()</code>查询当前建议的<code v-pre>gas</code>设置，返回的数据格式为<code v-pre>bigint</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 5. 查询当前建议的gas设置</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n5. 查询当前建议的gas设置"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> feeData <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getFeeData</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>feeData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-6.png" alt="getFeeData"></p>
<p><strong>6.</strong> 利用<code v-pre>getBlock()</code>查询区块信息，参数为要查询的区块高度：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 6. 查询区块信息</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n6. 查询区块信息"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> block <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBlock</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>block<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-7.png" alt="getBlock"></p>
<p><strong>7.</strong> 利用<code v-pre>getCode()</code>查询某个地址的合约<code v-pre>bytecode</code>，参数为合约地址，下面例子中用的主网<code v-pre>WETH</code>的合约地址：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 7. 给定合约地址查询合约bytecode，例子用的WETH地址</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n7. 给定合约地址查询合约bytecode，例子用的WETH地址"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> code <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getCode</span><span class="token punctuation">(</span><span class="token string">"0xc778417e063141139fce010982780140aa0cd5ab"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>code<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/2-8.png" alt="getCode"></p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 导入ethers包</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// playcode免费版不能安装ethers，用这条命令，需要从网络上import包（把上面这行注释掉）</span></span>
<span class="line"><span class="token comment">// import { ethers } from "https://cdn-cors.ethers.io/lib/ethers-5.6.9.esm.min.js";</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用公共rpc节点连接以太坊网络</span></span>
<span class="line"><span class="token comment">// 可以在 https://chainlist.org 上找到</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://rpc.ankr.com/eth'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_SEPOLIA_URL</span> <span class="token operator">=</span> <span class="token string">'https://rpc.sepolia.org'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 连接以太坊主网</span></span>
<span class="line"><span class="token keyword">const</span> providerETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 连接Sepolia测试网</span></span>
<span class="line"><span class="token keyword">const</span> providerSepolia <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_SEPOLIA_URL</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 利用provider读取链上信息</span></span>
<span class="line">    <span class="token comment">// 1. 查询vitalik在主网和Sepolia测试网的ETH余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"1. 查询vitalik在主网和Sepolia测试网的ETH余额"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> balance <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">vitalik.eth</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> balanceSepolia <span class="token operator">=</span> <span class="token keyword">await</span> providerSepolia<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// 将余额输出在console（主网）</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">ETH Balance of vitalik: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balance<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// 输出Sepolia测试网ETH余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Sepolia ETH Balance of vitalik: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceSepolia<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 2. 查询provider连接到了哪条链</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 查询provider连接到了哪条链"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> network <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getNetwork</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>network<span class="token punctuation">.</span><span class="token function">toJSON</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 3. 查询区块高度</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 查询区块高度"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> blockNumber <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBlockNumber</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>blockNumber<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 4. 查询 vitalik 钱包历史交易次数</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n4. 查询 vitalik 钱包历史交易次数"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> txCount <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span><span class="token string">"vitalik.eth"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>txCount<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 5. 查询当前建议的gas设置</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n5. 查询当前建议的gas设置"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> feeData <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getFeeData</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>feeData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 6. 查询区块信息</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n6. 查询区块信息"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> block <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getBlock</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>block<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 7. 给定合约地址查询合约bytecode，例子用的WETH地址</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n7. 给定合约地址查询合约bytecode，例子用的WETH地址"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> code <span class="token operator">=</span> <span class="token keyword">await</span> providerETH<span class="token punctuation">.</span><span class="token function">getCode</span><span class="token punctuation">(</span><span class="token string">"0xc778417e063141139fce010982780140aa0cd5ab"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>code<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


