<template><div><h1 id="_3-读取合约信息" tabindex="-1"><a class="header-anchor" href="#_3-读取合约信息"><span>3. 读取合约信息</span></a></h1>
<h2 id="contract类" tabindex="-1"><a class="header-anchor" href="#contract类"><span><code v-pre>Contract</code>类</span></a></h2>
<p>在<code v-pre>ethers</code>中，<code v-pre>Contract</code>类是部署在以太坊网络上的合约（<code v-pre>EVM</code>字节码）的抽象。通过它，开发者可以非常容易的对合约进行读取<code v-pre>call</code>和交易<code v-pre>transaction</code>，并可以获得交易的结果和事件。以太坊强大的地方正是合约，所以对于合约的操作要熟练掌握。</p>
<h2 id="创建contract变量" tabindex="-1"><a class="header-anchor" href="#创建contract变量"><span>创建<code v-pre>Contract</code>变量</span></a></h2>
<h3 id="只读和可读写contract" tabindex="-1"><a class="header-anchor" href="#只读和可读写contract"><span>只读和可读写<code v-pre>Contract</code></span></a></h3>
<p><code v-pre>Contract</code>对象分为两类，只读和可读写。只读<code v-pre>Contract</code>只能读取链上合约信息，执行<code v-pre>call</code>操作，即调用合约中<code v-pre>view</code>和<code v-pre>pure</code>的函数，而不能执行交易<code v-pre>transaction</code>。创建这两种<code v-pre>Contract</code>变量的方法有所不同：</p>
<ul>
<li>只读<code v-pre>Contract</code>：参数分别是合约地址，合约<code v-pre>abi</code>和<code v-pre>provider</code>变量（只读）。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> contract <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">address</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">abi</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">provider</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><ul>
<li>可读写<code v-pre>Contract</code>：参数分别是合约地址，合约<code v-pre>abi</code>和<code v-pre>signer</code>变量。<code v-pre>Signer</code>签名者是<code v-pre>ethers</code>中的另一个类，用于签名交易，之后我们会讲到。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> contract <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">address</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">abi</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">signer</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong>注意</strong> <code v-pre>ethers</code>中的<code v-pre>call</code>指的是只读操作，与<code v-pre>solidity</code>中的<code v-pre>call</code>不同。</p>
<h2 id="读取合约信息" tabindex="-1"><a class="header-anchor" href="#读取合约信息"><span>读取合约信息</span></a></h2>
<h3 id="_1-创建provider" tabindex="-1"><a class="header-anchor" href="#_1-创建provider"><span>1. 创建Provider</span></a></h3>
<p>我们使用Infura节点的API Key创建<code v-pre>Provider</code>（见<RouteLink to="/ethers/Provider.html">第2讲：Provider</RouteLink>）：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 利用Infura的rpc节点连接以太坊网络</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">INFURA_ID</span> <span class="token operator">=</span> <span class="token string">''</span></span>
<span class="line"><span class="token comment">// 连接以太坊主网</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">https://mainnet.infura.io/v3/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">INFURA_ID</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-创建只读contract实例" tabindex="-1"><a class="header-anchor" href="#_2-创建只读contract实例"><span>2. 创建只读Contract实例</span></a></h3>
<p>创建只读Contract实例需要填入<code v-pre>3</code>个参数，分别是合约地址，合约<code v-pre>abi</code>和<code v-pre>provider</code>变量。合约地址可以在网上查到，<code v-pre>provider</code>变量上一步我们已经创建了，那么<code v-pre>abi</code>怎么填？</p>
<p><code v-pre>ABI</code> (Application Binary Interface) 是与以太坊智能合约交互的标准。<code v-pre>ethers</code>支持两种<code v-pre>abi</code>填法：</p>
<ul>
<li><strong>方法1.</strong>  直接输入合约<code v-pre>abi</code>。你可以从<code v-pre>remix</code>的编译页面中复制，在本地编译合约时生成的<code v-pre>artifact</code>文件夹的<code v-pre>json</code>文件中得到，或者从<code v-pre>etherscan</code>开源合约的代码页面得到。我们用这个方法创建<code v-pre>WETH</code>的合约实例：</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 第1种输入abi的方式: 复制abi全文</span></span>
<span class="line"><span class="token comment">// WETH的abi可以在这里复制：https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code</span></span>
<span class="line"><span class="token keyword">const</span> abiWETH <span class="token operator">=</span> <span class="token string">'[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view",...太长后面省略...'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> addressWETH <span class="token operator">=</span> <span class="token string">'0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'</span> <span class="token comment">// WETH Contract</span></span>
<span class="line"><span class="token keyword">const</span> contractWETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressWETH<span class="token punctuation">,</span> abiWETH<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/3-1.png" alt="在Etherscan得到abi"></p>
<ul>
<li><strong>方法2.</strong> 由于<code v-pre>abi</code>可读性太差，<code v-pre>ethers</code>创新的引入了<code v-pre>Human-Readable Abi</code>（人类可读abi）。开发者可以通过<code v-pre>function signature</code>和<code v-pre>event signature</code>来写<code v-pre>abi</code>。我们用这个方法创建稳定币<code v-pre>DAI</code>的合约实例：</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 第2种输入abi的方式：输入程序需要用到的函数，逗号分隔，ethers会自动帮你转换成相应的abi</span></span>
<span class="line"><span class="token comment">// 人类可读abi，以ERC20合约为例</span></span>
<span class="line"><span class="token keyword">const</span> abiERC20 <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function totalSupply() view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) view returns (uint)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> addressDAI <span class="token operator">=</span> <span class="token string">'0x6B175474E89094C44Da98b954EedeAC495271d0F'</span> <span class="token comment">// DAI Contract</span></span>
<span class="line"><span class="token keyword">const</span> contractDAI <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressDAI<span class="token punctuation">,</span> abiERC20<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-读取weth和dai的链上信息" tabindex="-1"><a class="header-anchor" href="#_3-读取weth和dai的链上信息"><span>3. 读取<code v-pre>WETH</code>和<code v-pre>DAI</code>的链上信息</span></a></h3>
<p>我们可以利用只读<code v-pre>Contract</code>实例调用合约的<code v-pre>view</code>和<code v-pre>pure</code>函数，获取链上信息：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 1. 读取WETH合约的链上信息（WETH abi）</span></span>
<span class="line">    <span class="token keyword">const</span> nameWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> symbolWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> totalSupplyWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 读取WETH合约信息"</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>addressWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nameWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>symbolWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">总供给: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>totalSupplyWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token string">'vitalik.eth'</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Vitalik持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 2. 读取DAI合约的链上信息（IERC20接口合约）</span></span>
<span class="line">    <span class="token keyword">const</span> nameDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> symbolDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> totalSupplDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 读取DAI合约信息"</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>addressDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nameDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>symbolDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">总供给: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>totalSupplDAI<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token string">'vitalik.eth'</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Vitalik持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceDAI<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>可以看到，用两种方法创建的合约实例都能成功与链上交互。Vitalik的钱包里有<code v-pre>0.05 WETH</code>及<code v-pre>555508 DAI</code>，见下图。</p>
<p><img src="@source/ethers/img/3-2.png" alt="成功读取VitalikWETH和DAI持仓"></p>
<p><strong>说明</strong>
我们可以通过<a href="https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#readContract" target="_blank" rel="noopener noreferrer">以太坊浏览器</a> 验证Vitalik钱包里的<code v-pre>WETH</code>余额, 是否与通过<code v-pre>Contract</code>读取的一致。 通过<a href="https://app.ens.domains/name/vitalik.eth/details" target="_blank" rel="noopener noreferrer">ENS</a> 查到Vitalik钱包地址是<code v-pre>0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045</code>,然后通过合约方法<code v-pre>balanceOf</code>得到余额正好是<code v-pre>0.05 WETH</code>, 结论是一致！
<img src="@source/ethers/img/3-3.png" alt="VitalikWETH余额"></p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 声明只读合约的规则：</span></span>
<span class="line"><span class="token comment">// 参数分别为合约地址`address`，合约ABI `abi`，Provider变量`provider`</span></span>
<span class="line"><span class="token comment">// const contract = new ethers.Contract(`address`, `abi`, `provider`);</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊网络</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_MAINNET_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-mainnet.g.alchemy.com/v2/oKmOQKbneVkxgHZfibs-iFhIlIAl6HDN'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_MAINNET_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 第1种输入abi的方式: 复制abi全文</span></span>
<span class="line"><span class="token comment">// WETH的abi可以在这里复制：https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code</span></span>
<span class="line"><span class="token keyword">const</span> abiWETH <span class="token operator">=</span> <span class="token string">'[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"guy","type":"address"},{"name":"wad","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"src","type":"address"},{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"wad","type":"uint256"}],"name":"withdraw","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"deposit","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"guy","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Withdrawal","type":"event"}]'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> addressWETH <span class="token operator">=</span> <span class="token string">'0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'</span> <span class="token comment">// WETH Contract</span></span>
<span class="line"><span class="token keyword">const</span> contractWETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressWETH<span class="token punctuation">,</span> abiWETH<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 第2种输入abi的方式：输入程序需要用到的函数，逗号分隔，ethers会自动帮你转换成相应的abi</span></span>
<span class="line"><span class="token comment">// 人类可读abi，以ERC20合约为例</span></span>
<span class="line"><span class="token keyword">const</span> abiERC20 <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function totalSupply() view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) view returns (uint)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> addressDAI <span class="token operator">=</span> <span class="token string">'0x6B175474E89094C44Da98b954EedeAC495271d0F'</span> <span class="token comment">// DAI Contract</span></span>
<span class="line"><span class="token keyword">const</span> contractDAI <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressDAI<span class="token punctuation">,</span> abiERC20<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 1. 读取WETH合约的链上信息（WETH abi）</span></span>
<span class="line">    <span class="token keyword">const</span> nameWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> symbolWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> totalSupplyWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 读取WETH合约信息"</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>addressWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nameWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>symbolWETH<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">总供给: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>totalSupplyWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token string">'vitalik.eth'</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Vitalik持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 2. 读取DAI合约的链上信息（IERC20接口合约）</span></span>
<span class="line">    <span class="token keyword">const</span> nameDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> symbolDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> totalSupplDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">totalSupply</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 读取DAI合约信息"</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>addressDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nameDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>symbolDAI<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">总供给: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>totalSupplDAI<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceDAI <span class="token operator">=</span> <span class="token keyword">await</span> contractDAI<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token string">'vitalik.eth'</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Vitalik持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceDAI<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


