<template><div><h1 id="发送eth" tabindex="-1"><a class="header-anchor" href="#发送eth"><span>发送ETH</span></a></h1>
<h2 id="signer签名者类" tabindex="-1"><a class="header-anchor" href="#signer签名者类"><span><code v-pre>Signer</code>签名者类</span></a></h2>
<p><code v-pre>Web3.js</code>认为用户会在本地部署以太坊节点，私钥和网络连接状态由这个节点管理（实际并不是这样）；而在<code v-pre>ethers.js</code>中，<code v-pre>Provider</code>提供器类管理网络连接状态，<code v-pre>Signer</code>签名者类或<code v-pre>Wallet</code>钱包类管理密钥，安全且灵活。</p>
<p>在<code v-pre>ethers</code>中，<code v-pre>Signer</code>签名者类是以太坊账户的抽象，可用于对消息和交易进行签名，并将签名的交易发送到以太坊网络，并更改区块链状态。<code v-pre>Signer</code>类是抽象类，不能直接实例化，我们需要使用它的子类：<code v-pre>Wallet</code>钱包类。</p>
<h2 id="wallet钱包类" tabindex="-1"><a class="header-anchor" href="#wallet钱包类"><span><code v-pre>Wallet</code>钱包类</span></a></h2>
<p><code v-pre>Wallet</code>类继承了<code v-pre>Signer</code>类，并且开发者可以像包含私钥的外部拥有帐户（<code v-pre>EOA</code>）一样，用它对交易和消息进行签名。</p>
<p>下面我们介绍创建<code v-pre>Wallet</code>实例的几种办法：</p>
<h3 id="方法1-创建随机的wallet对象" tabindex="-1"><a class="header-anchor" href="#方法1-创建随机的wallet对象"><span>方法1：创建随机的wallet对象</span></a></h3>
<p>我们可以利用<code v-pre>ethers.Wallet.createRandom()</code>函数创建带有随机私钥的<code v-pre>Wallet</code>对象。该私钥由加密安全的熵源生成，如果当前环境没有安全的熵源，则会引发错误（没法在在线平台<code v-pre>playcode</code>使用此方法）。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 创建随机的wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet1 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="方法2-用私钥创建wallet对象" tabindex="-1"><a class="header-anchor" href="#方法2-用私钥创建wallet对象"><span>方法2：用私钥创建wallet对象</span></a></h3>
<p>我们已知私钥的情况下，可以利用<code v-pre>ethers.Wallet()</code>函数创建<code v-pre>Wallet</code>对象。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="方法3-从助记词创建wallet对象" tabindex="-1"><a class="header-anchor" href="#方法3-从助记词创建wallet对象"><span>方法3：从助记词创建wallet对象</span></a></h3>
<p>我们已知助记词的情况下，可以利用<code v-pre>ethers.Wallet.fromPhrase()</code>函数创建<code v-pre>Wallet</code>对象。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 从助记词创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet3 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">fromPhrase</span><span class="token punctuation">(</span>mnemonic<span class="token punctuation">.</span>phrase<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="其他方法-通过json文件创建wallet对象" tabindex="-1"><a class="header-anchor" href="#其他方法-通过json文件创建wallet对象"><span>其他方法：通过JSON文件创建wallet对象</span></a></h3>
<p>以上三种方法即可满足大部分需求，当然还可以通过<code v-pre>ethers.Wallet.fromEncryptedJson</code>解密一个<code v-pre>JSON</code>钱包文件创建钱包实例，<code v-pre>JSON</code>文件即<code v-pre>keystore</code>文件，通常来自<code v-pre>Geth</code>, <code v-pre>Parity</code>等钱包，通过<code v-pre>Geth</code>搭建过以太坊节点的个人对<code v-pre>keystore</code>文件不会陌生。</p>
<h2 id="发送eth-1" tabindex="-1"><a class="header-anchor" href="#发送eth-1"><span>发送<code v-pre>ETH</code></span></a></h2>
<p>我们可以利用<code v-pre>Wallet</code>实例来发送<code v-pre>ETH</code>。首先，我们要构造一个交易请求，在里面声明接收地址<code v-pre>to</code>和发送的<code v-pre>ETH</code>数额<code v-pre>value</code>。交易请求<code v-pre>TransactionRequest</code>类型可以包含发送方<code v-pre>from</code>，nonce值<code v-pre>nounce</code>，请求数据<code v-pre>data</code>等信息，之后的教程里会更详细介绍。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 创建交易请求，参数：to为接收地址，value为ETH数额</span></span>
<span class="line">    <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token literal-property property">to</span><span class="token operator">:</span> address1<span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">value</span><span class="token operator">:</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后，我们就可以利用<code v-pre>Wallet</code>类的<code v-pre>sendTransaction</code>来发送交易，等待交易上链，并获得交易的收据，非常简单。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">//发送交易，获得收据</span></span>
<span class="line">    <span class="token keyword">const</span> txRes <span class="token operator">=</span> <span class="token keyword">await</span> wallet2<span class="token punctuation">.</span><span class="token function">sendTransaction</span><span class="token punctuation">(</span>tx<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> receipt <span class="token operator">=</span> <span class="token keyword">await</span> txRes<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 等待链上确认交易</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>receipt<span class="token punctuation">)</span> <span class="token comment">// 打印交易的收据</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="代码示例" tabindex="-1"><a class="header-anchor" href="#代码示例"><span>代码示例</span></a></h2>
<h3 id="_1-创建provider实例" tabindex="-1"><a class="header-anchor" href="#_1-创建provider实例"><span>1. 创建<code v-pre>Provider</code>实例</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 利用Wallet类发送ETH</span></span>
<span class="line"><span class="token comment">// 由于playcode不支持ethers.Wallet.createRandom()函数，我们只能用VScode运行这一讲代码</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊测试网络</span></span>
<span class="line"><span class="token comment">// 准备 alchemy API 可以参考https://github.com/AmazingAng/WTFSolidity/blob/main/Topics/Tools/TOOL04_Alchemy/readme.md</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-用三种不同方法创建wallet实例" tabindex="-1"><a class="header-anchor" href="#_2-用三种不同方法创建wallet实例"><span>2. 用三种不同方法创建<code v-pre>Wallet</code>实例</span></a></h3>
<ul>
<li>创建随机私钥的<code v-pre>Wallet</code>对象。这种方法创建的钱包是单机的，我们需要用<code v-pre>connect(provider)</code>函数，连接到以太坊节点。这种方法创建的钱包可以用<code v-pre>mnemonic</code>获取助记词。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 创建随机的wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet1 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> wallet1WithProvider <span class="token operator">=</span> wallet1<span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span>provider<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> mnemonic <span class="token operator">=</span> wallet1<span class="token punctuation">.</span>mnemonic <span class="token comment">// 获取助记词</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>利用私钥和<code v-pre>Provider</code>实例创建<code v-pre>Wallet</code>对象。这种方法创建的钱包不能获取助记词。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>利用助记词创建<code v-pre>Wallet</code>对象。这里我们使用的是<code v-pre>wallet1</code>的助记词，因此创建出钱包的私钥和公钥都和<code v-pre>wallet1</code>相同。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 从助记词创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet3 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">fromPhrase</span><span class="token punctuation">(</span>mnemonic<span class="token punctuation">.</span>phrase<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-获取钱包地址" tabindex="-1"><a class="header-anchor" href="#_3-获取钱包地址"><span>3. 获取钱包地址</span></a></h3>
<p>利用<code v-pre>getAddress()</code>函数获取钱包地址。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token keyword">const</span> address1 <span class="token operator">=</span> <span class="token keyword">await</span> wallet1<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> address2 <span class="token operator">=</span> <span class="token keyword">await</span> wallet2<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> address3 <span class="token operator">=</span> <span class="token keyword">await</span> wallet3<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 获取地址</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">1. 获取钱包地址</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address1<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address2<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包3地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address3<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1和钱包3的地址是否相同: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address1 <span class="token operator">===</span> address3<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/4-1.png" alt="获取钱包地址"></p>
<h3 id="_4-获取助记词" tabindex="-1"><a class="header-anchor" href="#_4-获取助记词"><span>4. 获取助记词</span></a></h3>
<p>利用钱包对象的<code v-pre>mnemonic.phrase</code>成员获取助记词：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1助记词: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet1<span class="token punctuation">.</span>mnemonic<span class="token punctuation">.</span>phrase<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><img src="@source/ethers/img/4-2.png" alt="获取助记词"></p>
<h3 id="_5-获取私钥" tabindex="-1"><a class="header-anchor" href="#_5-获取私钥"><span>5. 获取私钥</span></a></h3>
<p>利用钱包对象的<code v-pre>privateKey</code>成员获取私钥：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2私钥: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet2<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><img src="@source/ethers/img/4-3.png" alt="获取私钥"></p>
<h3 id="_6-获取钱包在链上的交互次数" tabindex="-1"><a class="header-anchor" href="#_6-获取钱包在链上的交互次数"><span>6. 获取钱包在链上的交互次数</span></a></h3>
<p>利用<code v-pre>getTransactionCount()</code>函数获取钱包在链上的交互次数。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token keyword">const</span> txCount1 <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> txCount2 <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1发送交易次数: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txCount1<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2发送交易次数: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txCount2<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/4-4.png" alt="获取钱包在链上的交互次数"></p>
<h3 id="_7-发送eth" tabindex="-1"><a class="header-anchor" href="#_7-发送eth"><span>7. 发送<code v-pre>ETH</code></span></a></h3>
<p>我们用<code v-pre>wallet2</code>给<code v-pre>wallet1</code>发送<code v-pre>0.001 ETH</code>，并打印交易前后的钱包余额。由于<code v-pre>wallet1</code>是新建的随机私钥钱包，因此交易前余额为<code v-pre>0</code>，而交易后余额为<code v-pre>0.001 ETH</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    <span class="token comment">// 5. 发送ETH</span></span>
<span class="line">    <span class="token comment">// 如果这个钱包没goerli测试网ETH了，去水龙头领一些，钱包地址: 0xe16C1623c1AA7D919cd2241d8b36d9E79C1Be2A2</span></span>
<span class="line">    <span class="token comment">// 1. chainlink水龙头: https://faucets.chain.link/goerli</span></span>
<span class="line">    <span class="token comment">// 2. paradigm水龙头: https://faucet.paradigm.xyz/</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\n5. 发送ETH（测试网）</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// i. 打印交易前余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">i. 发送前余额</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// ii. 构造交易请求，参数：to为接收地址，value为ETH数额</span></span>
<span class="line">    <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token literal-property property">to</span><span class="token operator">:</span> address1<span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">value</span><span class="token operator">:</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token comment">// iii. 发送交易，获得收据</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\nii. 等待交易在区块链确认（需要几分钟）</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> receipt <span class="token operator">=</span> <span class="token keyword">await</span> wallet2<span class="token punctuation">.</span><span class="token function">sendTransaction</span><span class="token punctuation">(</span>tx<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">await</span> receipt<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 等待链上确认交易</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>receipt<span class="token punctuation">)</span> <span class="token comment">// 打印交易详情</span></span>
<span class="line">    <span class="token comment">// iv. 打印交易后余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\niii. 发送后余额</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/4-5.png" alt="发送ETH"></p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 利用Wallet类发送ETH</span></span>
<span class="line"><span class="token comment">// 由于playcode不支持ethers.Wallet.createRandom()函数，我们只能用VScode运行这一讲代码</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊测试网络</span></span>
<span class="line"><span class="token comment">// 准备 alchemy API 可以参考https://github.com/AmazingAng/WTFSolidity/blob/main/Topics/Tools/TOOL04_Alchemy/readme.md</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 创建随机的wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet1 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> wallet1WithProvider <span class="token operator">=</span> wallet1<span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span>provider<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> mnemonic <span class="token operator">=</span> wallet1<span class="token punctuation">.</span>mnemonic <span class="token comment">// 获取助记词</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 从助记词创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> wallet3 <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">fromPhrase</span><span class="token punctuation">(</span>mnemonic<span class="token punctuation">.</span>phrase<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 1. 获取钱包地址</span></span>
<span class="line">    <span class="token keyword">const</span> address1 <span class="token operator">=</span> <span class="token keyword">await</span> wallet1<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> address2 <span class="token operator">=</span> <span class="token keyword">await</span> wallet2<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> address3 <span class="token operator">=</span> <span class="token keyword">await</span> wallet3<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 获取地址</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">1. 获取钱包地址</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address1<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address2<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包3地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address3<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1和钱包3的地址是否相同: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>address1 <span class="token operator">===</span> address3<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 2. 获取助记词</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\n2. 获取助记词</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1助记词: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet1<span class="token punctuation">.</span>mnemonic<span class="token punctuation">.</span>phrase<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 注意：从private key生成的钱包没有助记词</span></span>
<span class="line">    <span class="token comment">// console.log(wallet2.mnemonic.phrase)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 3. 获取私钥</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\n3. 获取私钥</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1私钥: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet1<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2私钥: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet2<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 4. 获取链上发送交易次数</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\n4. 获取链上交易次数</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> txCount1 <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> txCount2 <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getTransactionCount</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1发送交易次数: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txCount1<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2发送交易次数: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>txCount2<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 5. 发送ETH</span></span>
<span class="line">    <span class="token comment">// 如果这个钱包没goerli测试网ETH了，去水龙头领一些，钱包地址: 0xe16C1623c1AA7D919cd2241d8b36d9E79C1Be2A2</span></span>
<span class="line">    <span class="token comment">// 1. chainlink水龙头: https://faucets.chain.link/goerli</span></span>
<span class="line">    <span class="token comment">// 2. paradigm水龙头: https://faucet.paradigm.xyz/</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\n5. 发送ETH（测试网）</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// i. 打印交易前余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">i. 发送前余额</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// ii. 构造交易请求，参数：to为接收地址，value为ETH数额</span></span>
<span class="line">    <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token literal-property property">to</span><span class="token operator">:</span> address1<span class="token punctuation">,</span></span>
<span class="line">        <span class="token literal-property property">value</span><span class="token operator">:</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token comment">// iii. 发送交易，获得收据</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\nii. 等待交易在区块链确认（需要几分钟）</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> receipt <span class="token operator">=</span> <span class="token keyword">await</span> wallet2<span class="token punctuation">.</span><span class="token function">sendTransaction</span><span class="token punctuation">(</span>tx<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">await</span> receipt<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 等待链上确认交易</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>receipt<span class="token punctuation">)</span> <span class="token comment">// 打印交易详情</span></span>
<span class="line">    <span class="token comment">// iv. 打印交易后余额</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">\niii. 发送后余额</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包1: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet1WithProvider<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包2: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span><span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet2<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> ETH</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


