<template><div><Layout/><h1 id="_18-数字签名脚本" tabindex="-1"><a class="header-anchor" href="#_18-数字签名脚本"><span>18. 数字签名脚本</span></a></h1>
<p>这一讲，我们介绍一个利用链下签名作为白名单发放<code v-pre>NFT</code>的方法。</p>
<h2 id="数字签名" tabindex="-1"><a class="header-anchor" href="#数字签名"><span>数字签名</span></a></h2>
<p>如果你用过<code v-pre>opensea</code>交易<code v-pre>NFT</code>，对签名就不会陌生。下图是小狐狸（<code v-pre>metamask</code>）钱包进行签名时弹出的窗口，它可以证明你拥有私钥的同时不需要对外公布私钥。</p>
<p><img src="@source/ethers/img/18-1.png" alt="metamask签名"></p>
<p>以太坊使用的数字签名算法叫双椭圆曲线数字签名算法（<code v-pre>ECDSA</code>），基于双椭圆曲线“私钥-公钥”对的数字签名算法。它主要起到了<a href="https://en.wikipedia.org/wiki/Digital_signature" target="_blank" rel="noopener noreferrer">三个作用</a>：</p>
<ol>
<li><strong>身份认证</strong>：证明签名方是私钥的持有人。</li>
<li><strong>不可否认</strong>：发送方不能否认发送过这个消息。</li>
<li><strong>完整性</strong>：消息在传输过程中无法被修改。</li>
</ol>
<h2 id="数字签名合约简述" tabindex="-1"><a class="header-anchor" href="#数字签名合约简述"><span>数字签名合约简述</span></a></h2>
<p><code v-pre>SignatureNFT</code>合约利用<code v-pre>ECDSA</code>验证白名单铸造<code v-pre>NFT</code>。我们讲下两个重要的函数：</p>
<ol>
<li>
<p>构造函数：初始化NFT的名称，代号，和签名公钥<code v-pre>signer</code>。</p>
</li>
<li>
<p><code v-pre>mint()</code>：利用<code v-pre>ECDSA</code>验证白名单地址并铸造。参数为白名单地址<code v-pre>account</code>，铸造的<code v-pre>tokenId</code>，和签名<code v-pre>signature</code>。</p>
</li>
</ol>
<h2 id="生成数字签名" tabindex="-1"><a class="header-anchor" href="#生成数字签名"><span>生成数字签名</span></a></h2>
<ol>
<li>
<p>打包消息：在以太坊的<code v-pre>ECDSA</code>标准中，被签名的<code v-pre>消息</code>是一组数据的<code v-pre>keccak256</code>哈希，为<code v-pre>bytes32</code>类型。我们可以利用<code v-pre>ethers.js</code>提供的<code v-pre>solidityPackedKeccak256()</code>函数，把任何想要签名的内容打包并计算哈希。等效于<code v-pre>solidity</code>中的<code v-pre>keccak256(abi.encodePacked())</code>。</p>
<p>在下面的代码中，我们将一个<code v-pre>address</code>类型变量和一个<code v-pre>uint256</code>类型变量打包后哈希，得到<code v-pre>消息</code>：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 创建消息</span></span>
<span class="line"><span class="token keyword">const</span> account <span class="token operator">=</span> <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span></span>
<span class="line"><span class="token keyword">const</span> tokenId <span class="token operator">=</span> <span class="token string">"0"</span></span>
<span class="line"><span class="token comment">// 等效于Solidity中的keccak256(abi.encodePacked(account, tokenId))</span></span>
<span class="line"><span class="token keyword">const</span> msgHash <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">solidityPackedKeccak256</span><span class="token punctuation">(</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token string">'address'</span><span class="token punctuation">,</span> <span class="token string">'uint256'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">[</span>account<span class="token punctuation">,</span> tokenId<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">msgHash：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>msgHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// msgHash：0x1bf2c0ce4546651a1a2feb457b39d891a6b83931cc2454434f39961345ac378c</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>签名：为了避免用户误签了恶意交易，<code v-pre>EIP191</code>提倡在<code v-pre>消息</code>前加上<code v-pre>&quot;\x19Ethereum Signed Message:\n32&quot;</code>字符，再做一次<code v-pre>keccak256</code>哈希得到<code v-pre>以太坊签名消息</code>，然后再签名。<code v-pre>ethers.js</code>的钱包类提供了<code v-pre>signMessage()</code>函数进行符合<code v-pre>EIP191</code>标准的签名。注意，如果<code v-pre>消息</code>为<code v-pre>string</code>类型，则需要利用<code v-pre>arrayify()</code>函数处理下。例子：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 签名</span></span>
<span class="line"><span class="token keyword">const</span> messageHashBytes <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getBytes</span><span class="token punctuation">(</span>msgHash<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> signature <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">signMessage</span><span class="token punctuation">(</span>messageHashBytes<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">签名：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>signature<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 签名：0x390d704d7ab732ce034203599ee93dd5d3cb0d4d1d7c600ac11726659489773d559b12d220f99f41d17651b0c1c6a669d346a397f8541760d6b32a5725378b241c</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
</ol>
<h2 id="链下签名白名单铸造nft" tabindex="-1"><a class="header-anchor" href="#链下签名白名单铸造nft"><span>链下签名白名单铸造<code v-pre>NFT</code></span></a></h2>
<ol>
<li>
<p>创建<code v-pre>provider</code>和<code v-pre>wallet</code>，其中<code v-pre>wallet</code>是用于签名的钱包。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>根据白名单地址和他们能铸造的<code v-pre>tokenId</code>生成<code v-pre>消息</code>并签名。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 创建消息</span></span>
<span class="line"><span class="token keyword">const</span> account <span class="token operator">=</span> <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span></span>
<span class="line"><span class="token keyword">const</span> tokenId <span class="token operator">=</span> <span class="token string">"0"</span></span>
<span class="line"><span class="token comment">// 等效于Solidity中的keccak256(abi.encodePacked(account, tokenId))</span></span>
<span class="line"><span class="token keyword">const</span> msgHash <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">solidityPackedKeccak256</span><span class="token punctuation">(</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token string">'address'</span><span class="token punctuation">,</span> <span class="token string">'uint256'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">[</span>account<span class="token punctuation">,</span> tokenId<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">msgHash：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>msgHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 签名</span></span>
<span class="line"><span class="token keyword">const</span> messageHashBytes <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getBytes</span><span class="token punctuation">(</span>msgHash<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> signature <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">signMessage</span><span class="token punctuation">(</span>messageHashBytes<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">签名：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>signature<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/18-2.png" alt="创建签名"></p>
</li>
<li>
<p>创建合约工厂，为部署<code v-pre>NFT</code>合约做准备。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// NFT的人类可读abi</span></span>
<span class="line"><span class="token keyword">const</span> abiNFT <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"constructor(string memory _name, string memory _symbol, address _signer)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function mint(address _account, uint256 _tokenId, bytes memory _signature) external"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function ownerOf(uint256) view returns (address)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 合约字节码，在remix中，你可以在两个地方找到Bytecode</span></span>
<span class="line"><span class="token comment">// i. 部署面板的Bytecode按钮</span></span>
<span class="line"><span class="token comment">// ii. 文件面板artifact文件夹下与合约同名的json文件中</span></span>
<span class="line"><span class="token comment">// 里面"object"字段对应的数据就是Bytecode，挺长的，608060起始</span></span>
<span class="line"><span class="token comment">// "object": "608060405260646000553480156100...</span></span>
<span class="line"><span class="token keyword">const</span> bytecodeNFT <span class="token operator">=</span> contractJson<span class="token punctuation">.</span>default<span class="token punctuation">.</span>object<span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> factoryNFT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>ContractFactory</span><span class="token punctuation">(</span>abiNFT<span class="token punctuation">,</span> bytecodeNFT<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>利用合约工厂部署NFT合约。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 部署合约，填入constructor的参数</span></span>
<span class="line"><span class="token keyword">const</span> contractNFT <span class="token operator">=</span> <span class="token keyword">await</span> factoryNFT<span class="token punctuation">.</span><span class="token function">deploy</span><span class="token punctuation">(</span><span class="token string">"WTF Signature"</span><span class="token punctuation">,</span> <span class="token string">"WTF"</span><span class="token punctuation">,</span> wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>contractNFT<span class="token punctuation">.</span>target<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"等待合约部署上链"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">waitForDeployment</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 也可以用 contractNFT.deployTransaction.wait()</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"合约已上链"</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/18-3.png" alt="部署NFT合约"></p>
</li>
<li>
<p>调用<code v-pre>NFT</code>合约的<code v-pre>mint()</code>函数，利用链下签名验证白名单，为<code v-pre>account</code>地址铸造<code v-pre>NFT</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">mint</span><span class="token punctuation">(</span>account<span class="token punctuation">,</span> tokenId<span class="token punctuation">,</span> signature<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"铸造中，等待交易上链"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint成功，地址</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>account<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> 的NFT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>account<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/18-4.png" alt="验证签名并铸造NFT"></p>
</li>
</ol>
<h2 id="用于生产环境" tabindex="-1"><a class="header-anchor" href="#用于生产环境"><span>用于生产环境</span></a></h2>
<p>在生产环境使用数字签名验证白名单发行<code v-pre>NFT</code>主要有以下步骤：</p>
<ol>
<li>确定白名单列表。</li>
<li>在后端维护一个签名钱包，生成每个白名单对应的<code v-pre>消息</code>和<code v-pre>签名</code>。</li>
<li>部署<code v-pre>NFT</code>合约，并将签名钱包的公钥<code v-pre>signer</code>保存在合约中。</li>
<li>用户铸造时，向后端请求地址对应的<code v-pre>签名</code>。</li>
<li>用户调用<code v-pre>mint()</code>函数进行铸造<code v-pre>NFT</code>。</li>
</ol>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 通过签名分发NFT白名单流程：</span></span>
<span class="line"><span class="token comment">//</span></span>
<span class="line"><span class="token comment">//    在服务器保管signer钱包的私钥-公钥对</span></span>
<span class="line"><span class="token comment">// -> 在服务器记录allowlist（白名单地址）和tokenId，并生成对应的msgHash，</span></span>
<span class="line"><span class="token comment">// -> 用signer钱包给msgHash签名</span></span>
<span class="line"><span class="token comment">// -> 部署NFT合约，初始化时signer的公钥保存在合约中。</span></span>
<span class="line"><span class="token comment">// -> 用户mint时填地址和tokenId，并向服务器请求签名。</span></span>
<span class="line"><span class="token comment">// -> 调用合约的mint()函数进行铸造</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token operator">*</span> <span class="token keyword">as</span> contractJson <span class="token keyword">from</span> <span class="token string">"./contract.json"</span> <span class="token keyword">assert</span> <span class="token punctuation">{</span><span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"json"</span><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 1. 创建provider和wallet</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 2. 根据allowlist地址和tokenId生成msgHash，并签名</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 生成签名"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 创建消息</span></span>
<span class="line"><span class="token keyword">const</span> account <span class="token operator">=</span> <span class="token string">"0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"</span></span>
<span class="line"><span class="token keyword">const</span> tokenId <span class="token operator">=</span> <span class="token string">"0"</span></span>
<span class="line"><span class="token comment">// 等效于Solidity中的keccak256(abi.encodePacked(account, tokenId))</span></span>
<span class="line"><span class="token keyword">const</span> msgHash <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">solidityPackedKeccak256</span><span class="token punctuation">(</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token string">'address'</span><span class="token punctuation">,</span> <span class="token string">'uint256'</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">[</span>account<span class="token punctuation">,</span> tokenId<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">msgHash：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>msgHash<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 签名</span></span>
<span class="line">    <span class="token keyword">const</span> messageHashBytes <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getBytes</span><span class="token punctuation">(</span>msgHash<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> signature <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">signMessage</span><span class="token punctuation">(</span>messageHashBytes<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">签名：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>signature<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 3. 创建合约工厂</span></span>
<span class="line">    <span class="token comment">// NFT的人类可读abi</span></span>
<span class="line">    <span class="token keyword">const</span> abiNFT <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">        <span class="token string">"constructor(string memory _name, string memory _symbol, address _signer)"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string">"function name() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string">"function symbol() view returns (string)"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string">"function mint(address _account, uint256 _tokenId, bytes memory _signature) external"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string">"function ownerOf(uint256) view returns (address)"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string">"function balanceOf(address) view returns (uint256)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// 合约字节码，在remix中，你可以在两个地方找到Bytecode</span></span>
<span class="line">    <span class="token comment">// i. 部署面板的Bytecode按钮</span></span>
<span class="line">    <span class="token comment">// ii. 文件面板artifact文件夹下与合约同名的json文件中</span></span>
<span class="line">    <span class="token comment">// 里面"object"字段对应的数据就是Bytecode，挺长的，608060起始</span></span>
<span class="line">    <span class="token comment">// "object": "608060405260646000553480156100...</span></span>
<span class="line">    <span class="token keyword">const</span> bytecodeNFT <span class="token operator">=</span> contractJson<span class="token punctuation">.</span>default<span class="token punctuation">.</span>object<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> factoryNFT <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>ContractFactory</span><span class="token punctuation">(</span>abiNFT<span class="token punctuation">,</span> bytecodeNFT<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 读取钱包内ETH余额</span></span>
<span class="line">    <span class="token keyword">const</span> balanceETH <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 如果钱包ETH足够</span></span>
<span class="line">    <span class="token keyword">if</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceETH<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">0.002</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 4. 利用contractFactory部署NFT合约</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 利用contractFactory部署NFT合约"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 部署合约，填入constructor的参数</span></span>
<span class="line">        <span class="token keyword">const</span> contractNFT <span class="token operator">=</span> <span class="token keyword">await</span> factoryNFT<span class="token punctuation">.</span><span class="token function">deploy</span><span class="token punctuation">(</span><span class="token string">"WTF Signature"</span><span class="token punctuation">,</span> <span class="token string">"WTF"</span><span class="token punctuation">,</span> wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">合约地址: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>contractNFT<span class="token punctuation">.</span>target<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"等待合约部署上链"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">waitForDeployment</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 也可以用 contractNFT.deployTransaction.wait()</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"合约已上链"</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// 5. 调用mint()函数，利用签名验证白名单，给account地址铸造NFT</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 调用mint()函数，利用签名验证白名单，给第一个地址铸造NFT"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT名称: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">NFT代号: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">symbol</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">let</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">mint</span><span class="token punctuation">(</span>account<span class="token punctuation">,</span> tokenId<span class="token punctuation">,</span> signature<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"铸造中，等待交易上链"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">mint成功，地址</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>account<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> 的NFT余额: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">await</span> contractNFT<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>account<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 如果ETH不足</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"ETH不足，去水龙头领一些Goerli ETH"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"1. chainlink水龙头: https://faucets.chain.link/goerli"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"2. paradigm水龙头: https://faucet.paradigm.xyz/"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


