<template><div><h1 id="_10-bigint和单位转换" tabindex="-1"><a class="header-anchor" href="#_10-bigint和单位转换"><span>10. BigInt和单位转换</span></a></h1>
<h2 id="bigint" tabindex="-1"><a class="header-anchor" href="#bigint"><span><code v-pre>BigInt</code></span></a></h2>
<p>以太坊中，许多计算都对超出<code v-pre>JavaScript</code>整数的安全值（js中最大安全整数为<code v-pre>9007199254740991</code>）。因此，<code v-pre>ethers.js</code>使用 JavaScript ES2020 版本原生的 <code v-pre>BigInt</code> 类 安全地对任何数量级的数字进行数学运算。在<code v-pre>ethers.js</code>中，大多数需要返回值的操作将返回 <code v-pre>BigInt</code>，而接受值的参数也会接受它们。</p>
<h3 id="创建bigint实例" tabindex="-1"><a class="header-anchor" href="#创建bigint实例"><span>创建<code v-pre>BigInt</code>实例</span></a></h3>
<p>你可以利用<code v-pre>ethers.getBigInt()</code>函数将<code v-pre>string</code>，<code v-pre>number</code>等类型转换为<code v-pre>BigInt</code>。</p>
<p><strong>注意</strong>，超过js最大安全整数的数值将不能转换。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> oneGwei <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token string">"1000000000"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 从十进制字符串生成</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token string">"0x3b9aca00"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 从hex字符串生成</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token number">1000000000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 从数字生成</span></span>
<span class="line"><span class="token comment">// 不能从js最大的安全整数之外的数字生成BigNumber，下面代码会报错</span></span>
<span class="line"><span class="token comment">// ethers.getBigInt(Number.MAX_SAFE_INTEGER);</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"js中最大安全整数："</span><span class="token punctuation">,</span> Number<span class="token punctuation">.</span><span class="token constant">MAX_SAFE_INTEGER</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/10-1.png" alt="BigNumber"></p>
<h3 id="bigint运算" tabindex="-1"><a class="header-anchor" href="#bigint运算"><span><code v-pre>BigInt</code>运算</span></a></h3>
<p><code v-pre>BigInt</code>支持很多运算，例如加减乘除、取模<code v-pre>mod</code>，幂运算<code v-pre>pow</code>，绝对值<code v-pre>abs</code>等运算:</p>
<blockquote>
<p>注意：数值带后缀<code v-pre>n</code>会自动转换成<code v-pre>BigInt</code></p>
</blockquote>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 运算</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"加法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">+</span> <span class="token number">1n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"减法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">-</span> <span class="token number">1n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"乘法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">*</span> <span class="token number">2n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"除法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">/</span> <span class="token number">2n</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 比较</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"是否相等："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">==</span> <span class="token number">1000000000n</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/10-2.png" alt="BigNumber运算"></p>
<h2 id="单位转换" tabindex="-1"><a class="header-anchor" href="#单位转换"><span>单位转换</span></a></h2>
<p>在以太坊中，<code v-pre>1 ether</code>等于<code v-pre>10^18 wei</code>。下面列出了一些常用的单位：</p>
<p><img src="@source/ethers/img/10-3.png" alt="常用单位"></p>
<p>在应用中，我们经常将数值在用户可读的字符串（以<code v-pre>ether</code>为单位）和机器可读的数值（以<code v-pre>wei</code>为单位）之间转换。例如，钱包可以为用户界面指定余额（以<code v-pre>ether</code>为单位）和<code v-pre>gas</code>价格（以<code v-pre>gwei</code>为单位），但是在发送交易时，两者都必须转换成以<code v-pre>wei</code>为单位的数值。<code v-pre>ethers.js</code>提供了一些功能函数，方便这类转换。</p>
<ul>
<li>
<p><code v-pre>formatUnits(变量, 单位)</code>：格式化，小单位转大单位，比如<code v-pre>wei</code> -&gt; <code v-pre>ether</code>，在显示余额时很有用。参数中，单位填位数（数字）或指定的单位（字符串）。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//代码参考：https://docs.ethers.org/v6/api/utils/#about-units</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token string">'\n2. 格式化：小单位转大单位，formatUnits'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1000000000'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token string">"ether"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// `0.000000001`</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span><span class="token number">1000000000</span><span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// `0.000000001` 等同于formatUnits(value, "ether")</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">groupEnd</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/10-4.png" alt="formatUnits"></p>
</li>
<li>
<p><code v-pre>parseUnits</code>：解析，大单位转小单位，比如<code v-pre>ether</code> -&gt; <code v-pre>wei</code>，在将用户输入的值转为<code v-pre>wei</code>为单位的数值很有用。参数中，单位填位数（数字）或指定的单位（字符串）。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 3. 解析：大单位转小单位</span></span>
<span class="line"><span class="token comment">// 例如将ether转换为wei：parseUnits(变量, 单位),parseUnits默认单位是 ether</span></span>
<span class="line"><span class="token comment">// 代码参考：https://docs.ethers.org/v6/api/utils/#about-units</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token string">'\n3. 解析：大单位转小单位，parseUnits'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token string">"ether"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token number">18</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" } 等同于parseUnits(value, "ether")</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">groupEnd</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/10-5.png" alt="parseUnits"></p>
</li>
</ul>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 1. BigNumber</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token string">'\n1. BigNumber类'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> oneGwei <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token string">"1000000000"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 从十进制字符串生成</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token string">"0x3b9aca00"</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 从hex字符串生成</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">getBigInt</span><span class="token punctuation">(</span><span class="token number">1000000000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 从数字生成</span></span>
<span class="line"><span class="token comment">// 不能从js最大的安全整数之外的数字生成BigNumber，下面代码会报错</span></span>
<span class="line"><span class="token comment">// ethers.getBigInt(Number.MAX_SAFE_INTEGER);</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"js中最大安全整数："</span><span class="token punctuation">,</span> Number<span class="token punctuation">.</span><span class="token constant">MAX_SAFE_INTEGER</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 运算</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"加法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">+</span> <span class="token number">1n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"减法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">-</span> <span class="token number">1n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"乘法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">*</span> <span class="token number">2n</span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"除法："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">/</span> <span class="token number">2n</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 比较</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"是否相等："</span><span class="token punctuation">,</span> oneGwei <span class="token operator">==</span> <span class="token number">1000000000n</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 2. 格式化：小单位转大单位</span></span>
<span class="line"><span class="token comment">// 例如将wei转换为ether：formatUnits(变量, 单位)：单位填位数（数字）或指定的单位（字符串）</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token string">'\n2. 格式化：小单位转大单位，formatUnits'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1000000000'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">,</span> <span class="token string">"ether"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// `0.000000001`</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatUnits</span><span class="token punctuation">(</span><span class="token number">1000000000</span><span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// '1.0'</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>oneGwei<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// `0.000000001` 等同于formatUnits(value, "ether")</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">groupEnd</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 3. 解析：大单位转小单位</span></span>
<span class="line"><span class="token comment">// 例如将ether转换为wei：parseUnits(变量, 单位),parseUnits默认单位是 ether</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token string">'\n3. 解析：大单位转小单位，parseUnits'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token string">"ether"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token number">18</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token string">"gwei"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseUnits</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000" }</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// { BigNumber: "1000000000000000000" } 等同于parseUnits(value, "ether")</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">groupEnd</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


