<template><div><h1 id="_21-靓号生成器" tabindex="-1"><a class="header-anchor" href="#_21-靓号生成器"><span>21. 靓号生成器</span></a></h1>
<p>这一讲，我们介绍如何利用<code v-pre>ethers.js</code>生成靓号地址，这是一个价值$1.6亿的教程（并不）。</p>
<h2 id="靓号地址" tabindex="-1"><a class="header-anchor" href="#靓号地址"><span>靓号地址</span></a></h2>
<p>现实生活中，有人追求车牌号“888888”，而在区块链中，大家也追求“靓号地址”。靓号地址（Vanity Address）是个性化的地址，易于识别，并且具有与其它地址一样的安全性。比如以<code v-pre>7</code>个<code v-pre>0</code>开头的地址：</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token number">0x0000000fe6a514a32abdcdfcc076c85243de899b</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>是的，这也是知名做市商<code v-pre>Wintermute</code>被盗$1.6亿的靓号地址（<a href="https://www.blocktempo.com/head-market-maker-wintermute-hacked-loses-160-million-magnesium/" target="_blank" rel="noopener noreferrer">报道</a>）。刚才我们说了，靓号和普通地址具有一样的安全性，那么这里为什么被攻击了呢？</p>
<p>问题出在生成靓号工具存在漏洞。<code v-pre>Wintermute</code>使用了一个叫<code v-pre>Profinity</code>的靓号生成器来生成地址，但这个生成器的随机种子有问题。本来随机种子应该有2的256次方可能性，但是<code v-pre>Profinity</code>使用的种子只有2的32次方的长度，可以被暴力破解。</p>
<h2 id="靓号生成器" tabindex="-1"><a class="header-anchor" href="#靓号生成器"><span>靓号生成器</span></a></h2>
<p>利用<code v-pre>ethers.js</code>，我们可以用<code v-pre>10</code>行代码就可以写出一个靓号生成器，它可能没有其它的工具快，但安全有保障。</p>
<h3 id="生成随机钱包" tabindex="-1"><a class="header-anchor" href="#生成随机钱包"><span>生成随机钱包</span></a></h3>
<p>我们可以利用下面的代码安全并随机的生成钱包：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 随机生成钱包，安全</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="正则表达式" tabindex="-1"><a class="header-anchor" href="#正则表达式"><span>正则表达式</span></a></h3>
<p>我们需要用正则表达式来筛选出目标靓号地址。这里简单的讲一下正则表达式：
- 开头几位字符匹配，我们用<code v-pre>^</code>符号，例如<code v-pre>^0x000</code>就会匹配以<code v-pre>0x000</code>开头的地址。
- 最后几位字符匹配，我们用<code v-pre>$</code>符号，例如<code v-pre>000$</code>就会匹配以<code v-pre>000</code>结尾的地址。
- 中间几位我们不关心，可以利用<code v-pre>.*</code>通配符，例如<code v-pre>^0x000.*000$</code>就会匹配任何以<code v-pre>0x000</code>开头并以<code v-pre>000</code>结尾的地址。</p>
<p>在<code v-pre>js</code>中，我们可以用下面的表达式筛选靓号地址：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^0x000.*$</span><span class="token regex-delimiter">/</span></span> <span class="token comment">// 表达式，匹配以0x000开头的地址</span></span>
<span class="line">isValid <span class="token operator">=</span> regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span> <span class="token comment">// 检验正则表达式</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="靓号生成脚本" tabindex="-1"><a class="header-anchor" href="#靓号生成脚本"><span>靓号生成脚本</span></a></h3>
<p>靓号生成器的逻辑非常简单，不断生成随机钱包，直到匹配到我们想要的靓号才结束。作为测试，以<code v-pre>0x000</code>开头的靓号仅需几秒就可以生成，每多一个<code v-pre>0</code>，耗时多16倍。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">var</span> wallet <span class="token comment">// 钱包</span></span>
<span class="line"><span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^0x000.*$</span><span class="token regex-delimiter">/</span></span> <span class="token comment">// 表达式</span></span>
<span class="line"><span class="token keyword">var</span> isValid <span class="token operator">=</span> <span class="token boolean">false</span></span>
<span class="line"><span class="token keyword">while</span><span class="token punctuation">(</span><span class="token operator">!</span>isValid<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    wallet <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 随机生成钱包，安全</span></span>
<span class="line">    isValid <span class="token operator">=</span> regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span> <span class="token comment">// 检验正则表达式</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token comment">// 打印靓号地址与私钥</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">靓号地址：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>address<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">靓号私钥：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/21-1.png" alt="靓号生成"></p>
<h2 id="扩展——顺序地址生成" tabindex="-1"><a class="header-anchor" href="#扩展——顺序地址生成"><span>扩展——顺序地址生成</span></a></h2>
<p>我们基于靓号生成器，扩充部分代码，批量生成指定开头的地址（比如001，002，…，999），以便在各种场景（空投交互）中进行简单的标识，方便自己进行管理。</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line">0x0017c58B5F7199198C490E7b602Dd559aC22EDcA:0x087922c19c90b41b2786968ee04300a34d99e8e556e71057ab7a30e9b8e34f4e</span>
<span class="line">0x0023F31fdc08FCD3296870F67e1eEC5d71bf2633:0x39f66b17c6ad3e8cc919f4d767fad2f8dd82a341b4431f4eb18365f52be7d0cd</span>
<span class="line">0x003a605E6E59B569bC37bb1287514357E311da34:0x2c4c787d155ef78e6d1ca364c808ec33a68937bead8bc7fd4eac360f6626d206</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果现在需要生成001、002、…、100，共计<code v-pre>100个</code>地址。那我们手动更改正则表达式工作量就太大了，因此使用循环进行处理，简单增加一个for循环和<code v-pre>padStart()</code>（填充补0，比如001，002）。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">var</span> wallet <span class="token comment">// 钱包</span></span>
<span class="line"><span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span> i <span class="token operator">&lt;=</span> <span class="token number">101</span><span class="token punctuation">;</span> i <span class="token operator">+=</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 填充3位数字，比如001，002，003，...，999</span></span>
<span class="line">    <span class="token keyword">const</span> paddedIndex <span class="token operator">=</span> <span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">padStart</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token string">'0'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">^0x</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>paddedIndex<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">.*$</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// 表达式</span></span>
<span class="line">    <span class="token keyword">var</span> isValid <span class="token operator">=</span> <span class="token boolean">false</span></span>
<span class="line">    <span class="token keyword">while</span><span class="token punctuation">(</span><span class="token operator">!</span>isValid<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        wallet <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// 随机生成钱包</span></span>
<span class="line">        isValid <span class="token operator">=</span> regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span> <span class="token comment">// 检验正则表达式</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token comment">// 打印地址与私钥</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包地址：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>address<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">钱包私钥：</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="时间问题" tabindex="-1"><a class="header-anchor" href="#时间问题"><span>时间问题</span></a></h3>
<p>但上述脚本实际使用时，耗费的时间是极其巨大的，因为上段中所用的脚本做了很多的重复工作，举个例子</p>
<p>有一个小游戏，面前的盒子中有编号1-10000的玻璃珠（编号会重复），需要从中找到编号1-100的玻璃珠，我们抓起一把，其中的编号是：<code v-pre>[1545,2,5,8544,6,44858,1112]</code>这其中<code v-pre>[2,5,6]</code>是符合条件的，那我们就需要把这三颗玻璃珠挑出，并且不再要这三个编号的珠子。</p>
<p>但是上段中的代码仅进行了简单的挑选，先挑选编号为<code v-pre>[1]</code>的玻璃珠，即使这把玻璃珠内恰好有<code v-pre>[2,3,…,99,100]</code>，也会将其丢弃，然后继续挑选步骤，这显然是不符合要求的，也是耗费时间过长的原因。</p>
<p>要解决这个问题，首先增加一个创建存有所有需要的正则表达式的数组。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 生成正则匹配表达式，并返回数组</span></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">CreateRegex</span><span class="token punctuation">(</span><span class="token parameter">total</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> regexList <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> index <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> index <span class="token operator">&lt;</span> total<span class="token punctuation">;</span> index<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 填充3位数字，比如001，002，003，...，999</span></span>
<span class="line">        <span class="token keyword">const</span> paddedIndex <span class="token operator">=</span> <span class="token punctuation">(</span>index <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">padStart</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token string">'0'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">^0x</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>paddedIndex<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">.*$</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        regexList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>regex<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> regexList<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>接着在生成钱包的函数中传入该数组并进行匹配，如匹配到则从数组中删除对应regex</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">CreateWallet</span><span class="token punctuation">(</span><span class="token parameter">regexList</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> wallet<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">var</span> isValid <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">while</span> <span class="token punctuation">(</span><span class="token operator">!</span>isValid <span class="token operator">&amp;&amp;</span> regexList<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        wallet <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">const</span> index <span class="token operator">=</span> regexList<span class="token punctuation">.</span><span class="token function">findIndex</span><span class="token punctuation">(</span><span class="token parameter">regex</span> <span class="token operator">=></span> regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token comment">// 移除匹配的正则表达式</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>index <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            isValid <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span></span>
<span class="line">            regexList<span class="token punctuation">.</span><span class="token function">splice</span><span class="token punctuation">(</span>index<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">const</span> data <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>address<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> data</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>此时时间缩短至可接受范围，测试生成100个顺序地址耗费时间大概为2分钟。</p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> fs <span class="token keyword">from</span> <span class="token string">"fs/promises"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 生成钱包，传入regexList数组并进行匹配，如匹配到则从数组中删除对应regex</span></span>
<span class="line"><span class="token keyword">async</span> <span class="token keyword">function</span> <span class="token function">CreateWallet</span><span class="token punctuation">(</span><span class="token parameter">regexList</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> wallet<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">var</span> isValid <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">while</span> <span class="token punctuation">(</span><span class="token operator">!</span>isValid <span class="token operator">&amp;&amp;</span> regexList<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        wallet <span class="token operator">=</span> ethers<span class="token punctuation">.</span>Wallet<span class="token punctuation">.</span><span class="token function">createRandom</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">const</span> index <span class="token operator">=</span> regexList<span class="token punctuation">.</span><span class="token function">findIndex</span><span class="token punctuation">(</span><span class="token parameter">regex</span> <span class="token operator">=></span> regex<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>wallet<span class="token punctuation">.</span>address<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token comment">// 移除匹配的正则表达式</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>index <span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            isValid <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span></span>
<span class="line">            regexList<span class="token punctuation">.</span><span class="token function">splice</span><span class="token punctuation">(</span>index<span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">const</span> data <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>address<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>wallet<span class="token punctuation">.</span>privateKey<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">return</span> data</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 生成正则匹配表达式，并返回数组</span></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">CreateRegex</span><span class="token punctuation">(</span><span class="token parameter">total</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> regexList <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> index <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> index <span class="token operator">&lt;</span> total<span class="token punctuation">;</span> index<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 填充3位数字，比如001，002，003，...，999</span></span>
<span class="line">        <span class="token keyword">const</span> paddedIndex <span class="token operator">=</span> <span class="token punctuation">(</span>index <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">padStart</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token string">'0'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">const</span> regex <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">^0x</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>paddedIndex<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">.*$</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        regexList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>regex<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> regexList<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 需要生成的钱包数量</span></span>
<span class="line"><span class="token keyword">const</span> total <span class="token operator">=</span> <span class="token number">20</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 生成正则表达式</span></span>
<span class="line"><span class="token keyword">const</span> regexL <span class="token operator">=</span> <span class="token function">CreateRegex</span><span class="token punctuation">(</span>total<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 数组存储生成地址</span></span>
<span class="line"><span class="token keyword">const</span> privateKeys <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> index <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span> index <span class="token operator">&lt;</span> total <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">;</span> index<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    privateKeys<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token keyword">await</span> <span class="token function">CreateWallet</span><span class="token punctuation">(</span>regexL<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 异步写入seeds.txt，因顺序生成钱包地址前三位，使用自带sort()函数即可排序，并在每个地址后添加换行符保存</span></span>
<span class="line"><span class="token keyword">await</span> fs<span class="token punctuation">.</span><span class="token function">appendFile</span><span class="token punctuation">(</span><span class="token string">'seeds.txt'</span><span class="token punctuation">,</span> privateKeys<span class="token punctuation">.</span><span class="token function">sort</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">'\n'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


