<template><div><Layout/><h1 id="_5-合约交互" tabindex="-1"><a class="header-anchor" href="#_5-合约交互"><span>5. 合约交互</span></a></h1>
<h2 id="创建可写contract变量" tabindex="-1"><a class="header-anchor" href="#创建可写contract变量"><span>创建可写<code v-pre>Contract</code>变量</span></a></h2>
<p>声明可写的<code v-pre>Contract</code>变量的规则：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> contract <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>address<span class="token punctuation">,</span> abi<span class="token punctuation">,</span> signer<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>其中<code v-pre>address</code>为合约地址，<code v-pre>abi</code>是合约的<code v-pre>abi</code>接口，<code v-pre>signer</code>是<code v-pre>wallet</code>对象。注意，这里你需要提供<code v-pre>signer</code>，而在声明可读合约时你只需要提供<code v-pre>provider</code>。</p>
<p>你也可以利用下面的方法，将可读合约转换为可写合约：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> contract2 <span class="token operator">=</span> contract<span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span>signer<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="合约交互" tabindex="-1"><a class="header-anchor" href="#合约交互"><span>合约交互</span></a></h2>
<p>我们在<RouteLink to="/ethers/ReadContract.html">第三讲</RouteLink>介绍了读取合约信息。它不需要<code v-pre>gas</code>。这里我们介绍写入合约信息，你需要构建交易，并且支付<code v-pre>gas</code>。该交易将由整个网络上的每个节点以及矿工验证，并改变区块链状态。</p>
<p>你可以用下面的方法进行合约交互：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 发送交易</span></span>
<span class="line"><span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contract<span class="token punctuation">.</span><span class="token constant">METHOD_NAME</span><span class="token punctuation">(</span>args <span class="token punctuation">[</span><span class="token punctuation">,</span> overrides<span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 等待链上确认交易</span></span>
<span class="line"><span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其中<code v-pre>METHOD_NAME</code>为调用的函数名，<code v-pre>args</code>为函数参数，<code v-pre>[, overrides]</code>是可以选择传入的数据，包括：</p>
<ul>
<li>gasPrice：gas价格</li>
<li>gasLimit：gas上限</li>
<li>value：调用时传入的ether（单位是wei）</li>
<li>nonce：nonce</li>
</ul>
<p><strong>注意：</strong> 此方法不能获取合约运行的返回值，如有需要，要使用<code v-pre>Solidity</code>事件记录，然后利用交易收据去查询。</p>
<h2 id="例子-与测试网weth合约交互" tabindex="-1"><a class="header-anchor" href="#例子-与测试网weth合约交互"><span>例子：与测试网<code v-pre>WETH</code>合约交互</span></a></h2>
<p><code v-pre>WETH</code> (Wrapped ETH)是<code v-pre>ETH</code>的带包装版本，将以太坊原生代币用智能合约包装成了符合<code v-pre>ERC20</code>的代币。</p>
<ol>
<li>
<p>创建<code v-pre>provider</code>，<code v-pre>wallet</code>变量。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊网络</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>创建可写<code v-pre>WETH</code>合约变量，我们在<code v-pre>ABI</code>中加入了4个我们要调用的函数：</p>
<ul>
<li><code v-pre>balanceOf(address)</code>：查询地址的<code v-pre>WETH</code>余额。</li>
<li><code v-pre>deposit()</code>：将转入合约的<code v-pre>ETH</code>转为<code v-pre>WETH</code>。</li>
<li><code v-pre>transfer(address, uint256)</code>：转账。</li>
<li><code v-pre>withdraw(uint256)</code>：取款。</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// WETH的ABI</span></span>
<span class="line"><span class="token keyword">const</span> abiWETH <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) public view returns(uint)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function deposit() public payable"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function transfer(address, uint) public returns (bool)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function withdraw(uint) public"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// WETH合约地址（Goerli测试网）</span></span>
<span class="line"><span class="token keyword">const</span> addressWETH <span class="token operator">=</span> <span class="token string">'0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6'</span> <span class="token comment">// WETH Contract</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 声明可写合约</span></span>
<span class="line"><span class="token keyword">const</span> contractWETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressWETH<span class="token punctuation">,</span> abiWETH<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 也可以声明一个只读合约，再用connect(wallet)函数转换成可写合约。</span></span>
<span class="line"><span class="token comment">// const contractWETH = new ethers.Contract(addressWETH, abiWETH, provider)</span></span>
<span class="line"><span class="token comment">// contractWETH.connect(wallet)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>读取账户<code v-pre>WETH</code>余额，可以看到余额为<code v-pre>1.001997</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> address <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 读取WETH合约的链上信息（WETH abi）</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 读取WETH余额"</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> balanceWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">存款前WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/5-1.png" alt="读取WETH余额"></p>
</li>
<li>
<p>调用<code v-pre>WETH</code>合约的<code v-pre>deposit()</code>函数，将<code v-pre>0.001 ETH</code>转换为<code v-pre>0.001 WETH</code>，打印交易详情和余额。<code v-pre>deposit()</code>函数没有参数，可以看到余额变为<code v-pre>1.002997</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 调用desposit()函数，存入0.001 ETH"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 发起交易</span></span>
<span class="line">    <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">deposit</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">value</span><span class="token operator">:</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 等待交易上链</span></span>
<span class="line">    <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">交易详情：</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>tx<span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceWETH_deposit <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">存款后WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH_deposit<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/5-2.png" alt="调用deposit"></p>
</li>
<li>
<p>调用<code v-pre>WETH</code>合约的<code v-pre>transfer()</code>函数，给Vitalik转账<code v-pre>0.001 WETH</code>，并打印余额。可以看到余额变为<code v-pre>1.001997</code>。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 调用transfer()函数，给vitalik转账0.001 WETH"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 发起交易</span></span>
<span class="line">    <span class="token keyword">const</span> tx2 <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">transfer</span><span class="token punctuation">(</span><span class="token string">"vitalik.eth"</span><span class="token punctuation">,</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 等待交易上链</span></span>
<span class="line">    <span class="token keyword">await</span> tx2<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceWETH_transfer <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">转账后WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH_transfer<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/ethers/img/5-3.png" alt="给Vitalik转WETH"></p>
</li>
</ol>
<p><strong>注意</strong>：观察<code v-pre>deposit()</code>函数和<code v-pre>balanceOf()</code>函数，为什么他们的返回值不一样？为什么前者返回一堆数据，而后者只返回确定的值？这是因为对于钱包的余额，它是一个只读操作，读到什么就是什么。而对于一次函数的调用，并不知道数据何时上链，所以只会返回这次交易的信息。总结来说，就是对于非<code v-pre>pure</code>/<code v-pre>view</code>函数的调用，会返回交易的信息。如果想知道函数执行过程中合约变量的变化，可以在合约中使用<code v-pre>emit</code>输出事件，并在返回的<code v-pre>transaction</code>信息中读取事件信息来获取相应的值。</p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码"><span>完整代码</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">// 声明只可写合约的规则：</span></span>
<span class="line"><span class="token comment">// const contract = new ethers.Contract(address, abi, signer);</span></span>
<span class="line"><span class="token comment">// 参数分别为合约地址`address`，合约ABI `abi`，Signer变量`signer`</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ethers <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// playcode免费版不能安装ethers，用这条命令，需要从网络上import包（把上面这行注释掉）</span></span>
<span class="line"><span class="token comment">// import { ethers } from "https://cdn-cors.ethers.io/lib/ethers-5.6.9.esm.min.js";</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用Alchemy的rpc节点连接以太坊网络</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token constant">ALCHEMY_GOERLI_URL</span> <span class="token operator">=</span> <span class="token string">'https://eth-goerli.alchemyapi.io/v2/GlaeWuylnNM3uuOo-SAwJxuwTdqHaY5l'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> provider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>JsonRpcProvider</span><span class="token punctuation">(</span><span class="token constant">ALCHEMY_GOERLI_URL</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 利用私钥和provider创建wallet对象</span></span>
<span class="line"><span class="token keyword">const</span> privateKey <span class="token operator">=</span> <span class="token string">'0x227dbb8586117d55284e26620bc76534dfbd2394be34cf4a09cb775d593b6f2b'</span></span>
<span class="line"><span class="token keyword">const</span> wallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Wallet</span><span class="token punctuation">(</span>privateKey<span class="token punctuation">,</span> provider<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// WETH的ABI</span></span>
<span class="line"><span class="token keyword">const</span> abiWETH <span class="token operator">=</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"function balanceOf(address) public view returns(uint)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function deposit() public payable"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function transfer(address, uint) public returns (bool)"</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string">"function withdraw(uint) public"</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// WETH合约地址（Goerli测试网）</span></span>
<span class="line"><span class="token keyword">const</span> addressWETH <span class="token operator">=</span> <span class="token string">'0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6'</span></span>
<span class="line"><span class="token comment">// WETH Contract</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 声明可写合约</span></span>
<span class="line"><span class="token keyword">const</span> contractWETH <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ethers<span class="token punctuation">.</span>Contract</span><span class="token punctuation">(</span>addressWETH<span class="token punctuation">,</span> abiWETH<span class="token punctuation">,</span> wallet<span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">// 也可以声明一个只读合约，再用connect(wallet)函数转换成可写合约。</span></span>
<span class="line"><span class="token comment">// const contractWETH = new ethers.Contract(addressWETH, abiWETH, provider)</span></span>
<span class="line"><span class="token comment">// contractWETH.connect(wallet)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">const</span> address <span class="token operator">=</span> <span class="token keyword">await</span> wallet<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">// 1. 读取WETH合约的链上信息（WETH abi）</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n1. 读取WETH余额"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">const</span> balanceWETH <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">存款前WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token comment">//读取钱包内ETH余额</span></span>
<span class="line">    <span class="token keyword">const</span> balanceETH <span class="token operator">=</span> <span class="token keyword">await</span> provider<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>wallet<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 如果钱包ETH足够</span></span>
<span class="line">    <span class="token keyword">if</span><span class="token punctuation">(</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceETH<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">0.0015</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// 2. 调用deposit()函数，将0.001 ETH转为WETH</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n2. 调用deposit()函数，存入0.001 ETH"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 发起交易</span></span>
<span class="line">        <span class="token keyword">const</span> tx <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">deposit</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">value</span><span class="token operator">:</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 等待交易上链</span></span>
<span class="line">        <span class="token keyword">await</span> tx<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">交易详情：</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>tx<span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">const</span> balanceWETH_deposit <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">存款后WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH_deposit<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// 3. 调用transfer()函数，将0.001 WETH转账给 vitalik</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\n3. 调用transfer()函数，给vitalik转账0.001 WETH"</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 发起交易</span></span>
<span class="line">        <span class="token keyword">const</span> tx2 <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">transfer</span><span class="token punctuation">(</span><span class="token string">"vitalik.eth"</span><span class="token punctuation">,</span> ethers<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.001"</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token comment">// 等待交易上链</span></span>
<span class="line">        <span class="token keyword">await</span> tx2<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token keyword">const</span> balanceWETH_transfer <span class="token operator">=</span> <span class="token keyword">await</span> contractWETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">转账后WETH持仓: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>ethers<span class="token punctuation">.</span><span class="token function">formatEther</span><span class="token punctuation">(</span>balanceWETH_transfer<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">\n</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">    <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// 如果ETH不足</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"ETH不足，去水龙头领一些Goerli ETH"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"1. chainlink水龙头: https://faucets.chain.link/goerli"</span><span class="token punctuation">)</span></span>
<span class="line">        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"2. paradigm水龙头: https://faucet.paradigm.xyz/"</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


