<template><div><Layout/><h1 id="_14-抽象合约和接口" tabindex="-1"><a class="header-anchor" href="#_14-抽象合约和接口"><span>14. 抽象合约和接口</span></a></h1>
<p>我们用<code v-pre>ERC721</code>的接口合约为例介绍<code v-pre>Solidity</code>中的抽象合约（<code v-pre>abstract</code>）和接口（<code v-pre>interface</code>），帮助大家更好的理解<code v-pre>ERC721</code>标准。</p>
<h2 id="抽象合约" tabindex="-1"><a class="header-anchor" href="#抽象合约"><span>抽象合约</span></a></h2>
<p>如果一个智能合约里至少有一个未实现的函数，即某个函数缺少主体<code v-pre>{}</code>中的内容，则必须将该合约标为<code v-pre>abstract</code>，不然编译会报错；另外，未实现的函数需要加<code v-pre>virtual</code>，以便子合约重写。拿我们之前的<RouteLink to="/Solidity/InsertionSort.html">插入排序合约</RouteLink>为例，如果我们还没想好具体怎么实现插入排序函数，那么可以把合约标为<code v-pre>abstract</code>，之后让别人补写上。</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line">abstract <span class="token keyword">contract</span> <span class="token class-name">InsertionSort</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">insertionSort</span><span class="token punctuation">(</span><span class="token builtin">uint</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token keyword">memory</span> a<span class="token punctuation">)</span> <span class="token keyword">public</span> <span class="token keyword">pure</span> virtual <span class="token keyword">returns</span><span class="token punctuation">(</span><span class="token builtin">uint</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token keyword">memory</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="接口" tabindex="-1"><a class="header-anchor" href="#接口"><span>接口</span></a></h2>
<p>接口类似于抽象合约，但它不实现任何功能。接口的规则：</p>
<ol>
<li>不能包含状态变量</li>
<li>不能包含构造函数</li>
<li>不能继承除接口外的其他合约</li>
<li>所有函数都必须是external且不能有函数体</li>
<li>继承接口的非抽象合约必须实现接口定义的所有功能</li>
</ol>
<p>虽然接口不实现任何功能，但它非常重要。接口是智能合约的骨架，定义了合约的功能以及如何触发它们：如果智能合约实现了某种接口（比如<code v-pre>ERC20</code>或<code v-pre>ERC721</code>），其他Dapps和智能合约就知道如何与它交互。因为接口提供了两个重要的信息：</p>
<ol>
<li>
<p>合约里每个函数的<code v-pre>bytes4</code>选择器，以及函数签名<code v-pre>函数名(每个参数类型）</code>。</p>
</li>
<li>
<p>接口id（更多信息见<a href="https://eips.ethereum.org/EIPS/eip-165" target="_blank" rel="noopener noreferrer">EIP165</a>）</p>
</li>
</ol>
<p>另外，接口与合约<code v-pre>ABI</code>（Application Binary Interface）等价，可以相互转换：编译接口可以得到合约的<code v-pre>ABI</code>，利用<a href="https://gnidan.github.io/abi-to-sol/" target="_blank" rel="noopener noreferrer">abi-to-sol工具</a>，也可以将<code v-pre>ABI json</code>文件转换为<code v-pre>接口sol</code>文件。</p>
<p>我们以<code v-pre>ERC721</code>接口合约<code v-pre>IERC721</code>为例，它定义了3个<code v-pre>event</code>和9个<code v-pre>function</code>，所有<code v-pre>ERC721</code>标准的NFT都实现了这些函数。我们可以看到，接口和常规合约的区别在于每个函数都以<code v-pre>;</code>代替函数体<code v-pre>{ }</code>结尾。</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token keyword">interface</span> <span class="token class-name">IERC721</span> <span class="token keyword">is</span> IERC165 <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> <span class="token keyword">indexed</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Approval</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> approved<span class="token punctuation">,</span> <span class="token builtin">uint256</span> <span class="token keyword">indexed</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">ApprovalForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> operator<span class="token punctuation">,</span> <span class="token builtin">bool</span> approved<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span> balance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">ownerOf</span><span class="token punctuation">(</span><span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">transferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">approve</span><span class="token punctuation">(</span><span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">getApproved</span><span class="token punctuation">(</span><span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">address</span> operator<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">setApprovalForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> operator<span class="token punctuation">,</span> <span class="token builtin">bool</span> _approved<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">isApprovedForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> operator<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">bool</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFrom</span><span class="token punctuation">(</span> <span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">,</span> <span class="token builtin">bytes</span> <span class="token keyword">calldata</span> data<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="ierc721事件" tabindex="-1"><a class="header-anchor" href="#ierc721事件"><span>IERC721事件</span></a></h3>
<p><code v-pre>IERC721</code>包含3个事件，其中<code v-pre>Transfer</code>和<code v-pre>Approval</code>事件在<code v-pre>ERC20</code>中也有。</p>
<ul>
<li><code v-pre>Transfer</code>事件：在转账时被释放，记录代币的发出地址<code v-pre>from</code>，接收地址<code v-pre>to</code>和<code v-pre>tokenId</code>。</li>
<li><code v-pre>Approval</code>事件：在授权时被释放，记录授权地址<code v-pre>owner</code>，被授权地址<code v-pre>approved</code>和<code v-pre>tokenId</code>。</li>
<li><code v-pre>ApprovalForAll</code>事件：在批量授权时被释放，记录批量授权的发出地址<code v-pre>owner</code>，被授权地址<code v-pre>operator</code>和授权与否的<code v-pre>approved</code>。</li>
</ul>
<h3 id="ierc721函数" tabindex="-1"><a class="header-anchor" href="#ierc721函数"><span>IERC721函数</span></a></h3>
<ul>
<li><code v-pre>balanceOf</code>：返回某地址的NFT持有量<code v-pre>balance</code>。</li>
<li><code v-pre>ownerOf</code>：返回某<code v-pre>tokenId</code>的主人<code v-pre>owner</code>。</li>
<li><code v-pre>transferFrom</code>：普通转账，参数为转出地址<code v-pre>from</code>，接收地址<code v-pre>to</code>和<code v-pre>tokenId</code>。</li>
<li><code v-pre>safeTransferFrom</code>：安全转账（如果接收方是合约地址，会要求实现<code v-pre>ERC721Receiver</code>接口）。参数为转出地址<code v-pre>from</code>，接收地址<code v-pre>to</code>和<code v-pre>tokenId</code>。</li>
<li><code v-pre>approve</code>：授权另一个地址使用你的NFT。参数为被授权地址<code v-pre>approve</code>和<code v-pre>tokenId</code>。</li>
<li><code v-pre>getApproved</code>：查询<code v-pre>tokenId</code>被批准给了哪个地址。</li>
<li><code v-pre>setApprovalForAll</code>：将自己持有的该系列NFT批量授权给某个地址<code v-pre>operator</code>。</li>
<li><code v-pre>isApprovedForAll</code>：查询某地址的NFT是否批量授权给了另一个<code v-pre>operator</code>地址。</li>
<li><code v-pre>safeTransferFrom</code>：安全转账的重载函数，参数里面包含了<code v-pre>data</code>。</li>
</ul>
<h3 id="什么时候使用接口" tabindex="-1"><a class="header-anchor" href="#什么时候使用接口"><span>什么时候使用接口？</span></a></h3>
<p>如果我们知道一个合约实现了<code v-pre>IERC721</code>接口，我们不需要知道它具体代码实现，就可以与它交互。</p>
<p>无聊猿<code v-pre>BAYC</code>属于<code v-pre>ERC721</code>代币，实现了<code v-pre>IERC721</code>接口的功能。我们不需要知道它的源代码，只需知道它的合约地址，用<code v-pre>IERC721</code>接口就可以与它交互，比如用<code v-pre>balanceOf()</code>来查询某个地址的<code v-pre>BAYC</code>余额，用<code v-pre>safeTransferFrom()</code>来转账<code v-pre>BAYC</code>。</p>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token keyword">contract</span> <span class="token class-name">interactBAYC</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 利用BAYC地址创建接口合约变量（ETH主网）</span></span>
<span class="line">    IERC721 BAYC <span class="token operator">=</span> <span class="token function">IERC721</span><span class="token punctuation">(</span><span class="token number">0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 通过接口调用BAYC的balanceOf()查询持仓量</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">balanceOfBAYC</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span> balance<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">return</span> BAYC<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>owner<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 通过接口调用BAYC的safeTransferFrom()安全转账</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFromBAYC</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">{</span></span>
<span class="line">        BAYC<span class="token punctuation">.</span><span class="token function">safeTransferFrom</span><span class="token punctuation">(</span><span class="token keyword">from</span><span class="token punctuation">,</span> to<span class="token punctuation">,</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="在remix上验证" tabindex="-1"><a class="header-anchor" href="#在remix上验证"><span>在Remix上验证</span></a></h2>
<ul>
<li>
<p>抽象合约示例（简单的演示代码如图所示）</p>
<p><img src="@source/Solidity/img/14-1.png" alt="14-1"></p>
</li>
<li>
<p>接口示例（简单的演示代码如图所示）</p>
<p><img src="@source/Solidity/img/14-2.png" alt="14-2"></p>
</li>
</ul>
<h2 id="完整合约" tabindex="-1"><a class="header-anchor" href="#完整合约"><span>完整合约</span></a></h2>
<div class="language-solidity line-numbers-mode" data-highlighter="prismjs" data-ext="solidity" data-title="solidity"><pre v-pre><code><span class="line"><span class="token comment">// SPDX-License-Identifier: MIT</span></span>
<span class="line"><span class="token keyword">pragma</span> <span class="token keyword">solidity</span> <span class="token operator">^</span><span class="token version number">0.8.21</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">abstract <span class="token keyword">contract</span> <span class="token class-name">InsertionSort</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">insertionSort</span><span class="token punctuation">(</span><span class="token builtin">uint</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token keyword">memory</span> a<span class="token punctuation">)</span> <span class="token keyword">public</span> <span class="token keyword">pure</span> virtual <span class="token keyword">returns</span><span class="token punctuation">(</span><span class="token builtin">uint</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token keyword">memory</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"@openzeppelin/contracts/utils/introspection/IERC165.sol"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">interface</span> <span class="token class-name">IERC721</span> <span class="token keyword">is</span> IERC165 <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Transfer</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> <span class="token keyword">indexed</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">Approval</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> approved<span class="token punctuation">,</span> <span class="token builtin">uint256</span> <span class="token keyword">indexed</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">event</span> <span class="token function">ApprovalForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">indexed</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> <span class="token keyword">indexed</span> operator<span class="token punctuation">,</span> <span class="token builtin">bool</span> approved<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span> balance<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">ownerOf</span><span class="token punctuation">(</span><span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">transferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">approve</span><span class="token punctuation">(</span><span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">getApproved</span><span class="token punctuation">(</span><span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">address</span> operator<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">setApprovalForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> operator<span class="token punctuation">,</span> <span class="token builtin">bool</span> _approved<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">isApprovedForAll</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">,</span> <span class="token builtin">address</span> operator<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">bool</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFrom</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">,</span> <span class="token builtin">bytes</span> <span class="token keyword">calldata</span> data<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">contract</span> <span class="token class-name">interactBAYC</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 利用BAYC地址创建接口合约变量（ETH主网）</span></span>
<span class="line">    IERC721 BAYC <span class="token operator">=</span> <span class="token function">IERC721</span><span class="token punctuation">(</span><span class="token number">0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 通过接口调用BAYC的balanceOf()查询持仓量</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">balanceOfBAYC</span><span class="token punctuation">(</span><span class="token builtin">address</span> owner<span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">view</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token builtin">uint256</span> balance<span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">return</span> BAYC<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span>owner<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// 通过接口调用BAYC的safeTransferFrom()安全转账</span></span>
<span class="line">    <span class="token keyword">function</span> <span class="token function">safeTransferFromBAYC</span><span class="token punctuation">(</span><span class="token builtin">address</span> <span class="token keyword">from</span><span class="token punctuation">,</span> <span class="token builtin">address</span> to<span class="token punctuation">,</span> <span class="token builtin">uint256</span> tokenId<span class="token punctuation">)</span> <span class="token keyword">external</span><span class="token punctuation">{</span></span>
<span class="line">        BAYC<span class="token punctuation">.</span><span class="token function">safeTransferFrom</span><span class="token punctuation">(</span><span class="token keyword">from</span><span class="token punctuation">,</span> to<span class="token punctuation">,</span> tokenId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


